//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:ContractAccountUpdate", ConfigurationName="Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOut")]
    public interface ContractAccountUpdateOut {
        
        // CODEGEN: Generating message contract since the operation ContractAccountUpdateOut is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOutResponse ContractAccountUpdateOut(Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOutResponse> ContractAccountUpdateOutAsync(Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class ContractAccountUpdateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Admin adminField;
        
        private KontoUmowyAktualizacja aktualizujKontoUmowyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Admin Admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
                this.RaisePropertyChanged("Admin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public KontoUmowyAktualizacja AktualizujKontoUmowy {
            get {
                return this.aktualizujKontoUmowyField;
            }
            set {
                this.aktualizujKontoUmowyField = value;
                this.RaisePropertyChanged("AktualizujKontoUmowy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Admin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jednostkaGospodarczaField;
        
        private string iDKomunikatuField;
        
        private string iDSystemMerytorycznegoField;
        
        private string utworzonyDataField;
        
        private string utworzonyGodzField;
        
        private string uzytkownikField;
        
        private string hasloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string JednostkaGospodarcza {
            get {
                return this.jednostkaGospodarczaField;
            }
            set {
                this.jednostkaGospodarczaField = value;
                this.RaisePropertyChanged("JednostkaGospodarcza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IDSystemMerytorycznego {
            get {
                return this.iDSystemMerytorycznegoField;
            }
            set {
                this.iDSystemMerytorycznegoField = value;
                this.RaisePropertyChanged("IDSystemMerytorycznego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UtworzonyData {
            get {
                return this.utworzonyDataField;
            }
            set {
                this.utworzonyDataField = value;
                this.RaisePropertyChanged("UtworzonyData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string UtworzonyGodz {
            get {
                return this.utworzonyGodzField;
            }
            set {
                this.utworzonyGodzField = value;
                this.RaisePropertyChanged("UtworzonyGodz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Uzytkownik {
            get {
                return this.uzytkownikField;
            }
            set {
                this.uzytkownikField = value;
                this.RaisePropertyChanged("Uzytkownik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Haslo {
            get {
                return this.hasloField;
            }
            set {
                this.hasloField = value;
                this.RaisePropertyChanged("Haslo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Komunikat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDKomunikatuField;
        
        private string rodzajKomunikatuField;
        
        private string numerKomunikatuField;
        
        private string komunikat1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RodzajKomunikatu {
            get {
                return this.rodzajKomunikatuField;
            }
            set {
                this.rodzajKomunikatuField = value;
                this.RaisePropertyChanged("RodzajKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NumerKomunikatu {
            get {
                return this.numerKomunikatuField;
            }
            set {
                this.numerKomunikatuField = value;
                this.RaisePropertyChanged("NumerKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Komunikat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Komunikat1 {
            get {
                return this.komunikat1Field;
            }
            set {
                this.komunikat1Field = value;
                this.RaisePropertyChanged("Komunikat1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class ContractAccountUpdateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Komunikat[] komunikatyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Komunikat[] Komunikaty {
            get {
                return this.komunikatyField;
            }
            set {
                this.komunikatyField = value;
                this.RaisePropertyChanged("Komunikaty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class KontoUmowyAktualizacja : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numerKontaUmowyField;
        
        private string numerPartneraField;
        
        private string iDPrzedmiotuUmowyField;
        
        private string mikrorachunekField;
        
        private string oznaczenieKontaUmowyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NumerKontaUmowy {
            get {
                return this.numerKontaUmowyField;
            }
            set {
                this.numerKontaUmowyField = value;
                this.RaisePropertyChanged("NumerKontaUmowy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NumerPartnera {
            get {
                return this.numerPartneraField;
            }
            set {
                this.numerPartneraField = value;
                this.RaisePropertyChanged("NumerPartnera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IDPrzedmiotuUmowy {
            get {
                return this.iDPrzedmiotuUmowyField;
            }
            set {
                this.iDPrzedmiotuUmowyField = value;
                this.RaisePropertyChanged("IDPrzedmiotuUmowy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Mikrorachunek {
            get {
                return this.mikrorachunekField;
            }
            set {
                this.mikrorachunekField = value;
                this.RaisePropertyChanged("Mikrorachunek");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string OznaczenieKontaUmowy {
            get {
                return this.oznaczenieKontaUmowyField;
            }
            set {
                this.oznaczenieKontaUmowyField = value;
                this.RaisePropertyChanged("OznaczenieKontaUmowy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContractAccountUpdateOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:ContractAccountUpdate", Order=0)]
        public Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateRequest ContractAccountUpdateRequest;
        
        public ContractAccountUpdateOutRequest() {
        }
        
        public ContractAccountUpdateOutRequest(Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateRequest ContractAccountUpdateRequest) {
            this.ContractAccountUpdateRequest = ContractAccountUpdateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContractAccountUpdateOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:ContractAccountUpdate", Order=0)]
        public Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateResponse ContractAccountUpdateResponse;
        
        public ContractAccountUpdateOutResponse() {
        }
        
        public ContractAccountUpdateOutResponse(Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateResponse ContractAccountUpdateResponse) {
            this.ContractAccountUpdateResponse = ContractAccountUpdateResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContractAccountUpdateOutChannel : Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOut, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContractAccountUpdateOutClient : System.ServiceModel.ClientBase<Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOut>, Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOut {
        
        public ContractAccountUpdateOutClient() {
        }
        
        public ContractAccountUpdateOutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContractAccountUpdateOutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractAccountUpdateOutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractAccountUpdateOutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOutResponse Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOut.ContractAccountUpdateOut(Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOutRequest request) {
            return base.Channel.ContractAccountUpdateOut(request);
        }
        
        public Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateResponse ContractAccountUpdateOut(Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateRequest ContractAccountUpdateRequest) {
            Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOutRequest inValue = new Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOutRequest();
            inValue.ContractAccountUpdateRequest = ContractAccountUpdateRequest;
            Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOutResponse retVal = ((Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOut)(this)).ContractAccountUpdateOut(inValue);
            return retVal.ContractAccountUpdateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOutResponse> Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOut.ContractAccountUpdateOutAsync(Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOutRequest request) {
            return base.Channel.ContractAccountUpdateOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOutResponse> ContractAccountUpdateOutAsync(Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateRequest ContractAccountUpdateRequest) {
            Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOutRequest inValue = new Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOutRequest();
            inValue.ContractAccountUpdateRequest = ContractAccountUpdateRequest;
            return ((Ex2PscdInterface.Ex2PscdContractAccountUpdateOutService.ContractAccountUpdateOut)(this)).ContractAccountUpdateOutAsync(inValue);
        }
    }
}
