//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex2PscdInterface.Ex2PscdDocumentUpdateOutService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:DocumentUpdate", ConfigurationName="Ex2PscdDocumentUpdateOutService.DocumentUpdateOut")]
    public interface DocumentUpdateOut {
        
        // CODEGEN: Generating message contract since the operation DocumentUpdateOut is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOutResponse DocumentUpdateOut(Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOutResponse> DocumentUpdateOutAsync(Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class DocumentUpdateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Admin adminField;
        
        private ZmianaTerminu zmianaTerminuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Admin Admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
                this.RaisePropertyChanged("Admin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ZmianaTerminu ZmianaTerminu {
            get {
                return this.zmianaTerminuField;
            }
            set {
                this.zmianaTerminuField = value;
                this.RaisePropertyChanged("ZmianaTerminu");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Admin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jednostkaGospodarczaField;
        
        private string iDKomunikatuField;
        
        private string iDSystemMerytorycznegoField;
        
        private string utworzonyDataField;
        
        private string utworzonyGodzField;
        
        private string uzytkownikField;
        
        private string hasloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string JednostkaGospodarcza {
            get {
                return this.jednostkaGospodarczaField;
            }
            set {
                this.jednostkaGospodarczaField = value;
                this.RaisePropertyChanged("JednostkaGospodarcza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IDSystemMerytorycznego {
            get {
                return this.iDSystemMerytorycznegoField;
            }
            set {
                this.iDSystemMerytorycznegoField = value;
                this.RaisePropertyChanged("IDSystemMerytorycznego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UtworzonyData {
            get {
                return this.utworzonyDataField;
            }
            set {
                this.utworzonyDataField = value;
                this.RaisePropertyChanged("UtworzonyData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string UtworzonyGodz {
            get {
                return this.utworzonyGodzField;
            }
            set {
                this.utworzonyGodzField = value;
                this.RaisePropertyChanged("UtworzonyGodz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Uzytkownik {
            get {
                return this.uzytkownikField;
            }
            set {
                this.uzytkownikField = value;
                this.RaisePropertyChanged("Uzytkownik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Haslo {
            get {
                return this.hasloField;
            }
            set {
                this.hasloField = value;
                this.RaisePropertyChanged("Haslo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Komunikat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDKomunikatuField;
        
        private string rodzajKomunikatuField;
        
        private string numerKomunikatuField;
        
        private string komunikat1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RodzajKomunikatu {
            get {
                return this.rodzajKomunikatuField;
            }
            set {
                this.rodzajKomunikatuField = value;
                this.RaisePropertyChanged("RodzajKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NumerKomunikatu {
            get {
                return this.numerKomunikatuField;
            }
            set {
                this.numerKomunikatuField = value;
                this.RaisePropertyChanged("NumerKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Komunikat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Komunikat1 {
            get {
                return this.komunikat1Field;
            }
            set {
                this.komunikat1Field = value;
                this.RaisePropertyChanged("Komunikat1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class DocumentUpdateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Komunikat[] komunikatyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Komunikat[] Komunikaty {
            get {
                return this.komunikatyField;
            }
            set {
                this.komunikatyField = value;
                this.RaisePropertyChanged("Komunikaty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class ZmianaTerminu : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numerDokumentuField;
        
        private string dataOdroczeniaField;
        
        private string dataWymagalnosciField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NumerDokumentu {
            get {
                return this.numerDokumentuField;
            }
            set {
                this.numerDokumentuField = value;
                this.RaisePropertyChanged("NumerDokumentu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DataOdroczenia {
            get {
                return this.dataOdroczeniaField;
            }
            set {
                this.dataOdroczeniaField = value;
                this.RaisePropertyChanged("DataOdroczenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DataWymagalnosci {
            get {
                return this.dataWymagalnosciField;
            }
            set {
                this.dataWymagalnosciField = value;
                this.RaisePropertyChanged("DataWymagalnosci");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocumentUpdateOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:DocumentUpdate", Order=0)]
        public Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateRequest DocumentUpdateRequest;
        
        public DocumentUpdateOutRequest() {
        }
        
        public DocumentUpdateOutRequest(Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateRequest DocumentUpdateRequest) {
            this.DocumentUpdateRequest = DocumentUpdateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocumentUpdateOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:DocumentUpdate", Order=0)]
        public Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateResponse DocumentUpdateResponse;
        
        public DocumentUpdateOutResponse() {
        }
        
        public DocumentUpdateOutResponse(Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateResponse DocumentUpdateResponse) {
            this.DocumentUpdateResponse = DocumentUpdateResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocumentUpdateOutChannel : Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOut, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentUpdateOutClient : System.ServiceModel.ClientBase<Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOut>, Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOut {
        
        public DocumentUpdateOutClient() {
        }
        
        public DocumentUpdateOutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentUpdateOutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentUpdateOutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentUpdateOutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOutResponse Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOut.DocumentUpdateOut(Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOutRequest request) {
            return base.Channel.DocumentUpdateOut(request);
        }
        
        public Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateResponse DocumentUpdateOut(Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateRequest DocumentUpdateRequest) {
            Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOutRequest inValue = new Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOutRequest();
            inValue.DocumentUpdateRequest = DocumentUpdateRequest;
            Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOutResponse retVal = ((Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOut)(this)).DocumentUpdateOut(inValue);
            return retVal.DocumentUpdateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOutResponse> Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOut.DocumentUpdateOutAsync(Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOutRequest request) {
            return base.Channel.DocumentUpdateOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOutResponse> DocumentUpdateOutAsync(Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateRequest DocumentUpdateRequest) {
            Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOutRequest inValue = new Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOutRequest();
            inValue.DocumentUpdateRequest = DocumentUpdateRequest;
            return ((Ex2PscdInterface.Ex2PscdDocumentUpdateOutService.DocumentUpdateOut)(this)).DocumentUpdateOutAsync(inValue);
        }
    }
}
