//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:PaymentClarificationsQuery", ConfigurationName="Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOut")]
    public interface PaymentClarificationsQueryOut {
        
        // CODEGEN: Generating message contract since the operation PaymentClarificationsQueryOut is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOutResponse PaymentClarificationsQueryOut(Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOutResponse> PaymentClarificationsQueryOutAsync(Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class PaymentClarificationsQueryRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Admin adminField;
        
        private string dataKsiegowaniaOdField;
        
        private string dataKsiegowaniaDoField;
        
        private string dataKsStornaOdField;
        
        private string dataKsStornaDoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Admin Admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
                this.RaisePropertyChanged("Admin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DataKsiegowaniaOd {
            get {
                return this.dataKsiegowaniaOdField;
            }
            set {
                this.dataKsiegowaniaOdField = value;
                this.RaisePropertyChanged("DataKsiegowaniaOd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DataKsiegowaniaDo {
            get {
                return this.dataKsiegowaniaDoField;
            }
            set {
                this.dataKsiegowaniaDoField = value;
                this.RaisePropertyChanged("DataKsiegowaniaDo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DataKsStornaOd {
            get {
                return this.dataKsStornaOdField;
            }
            set {
                this.dataKsStornaOdField = value;
                this.RaisePropertyChanged("DataKsStornaOd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DataKsStornaDo {
            get {
                return this.dataKsStornaDoField;
            }
            set {
                this.dataKsStornaDoField = value;
                this.RaisePropertyChanged("DataKsStornaDo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Admin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jednostkaGospodarczaField;
        
        private string iDKomunikatuField;
        
        private string iDSystemMerytorycznegoField;
        
        private string utworzonyDataField;
        
        private string utworzonyGodzField;
        
        private string uzytkownikField;
        
        private string hasloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string JednostkaGospodarcza {
            get {
                return this.jednostkaGospodarczaField;
            }
            set {
                this.jednostkaGospodarczaField = value;
                this.RaisePropertyChanged("JednostkaGospodarcza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IDSystemMerytorycznego {
            get {
                return this.iDSystemMerytorycznegoField;
            }
            set {
                this.iDSystemMerytorycznegoField = value;
                this.RaisePropertyChanged("IDSystemMerytorycznego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UtworzonyData {
            get {
                return this.utworzonyDataField;
            }
            set {
                this.utworzonyDataField = value;
                this.RaisePropertyChanged("UtworzonyData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string UtworzonyGodz {
            get {
                return this.utworzonyGodzField;
            }
            set {
                this.utworzonyGodzField = value;
                this.RaisePropertyChanged("UtworzonyGodz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Uzytkownik {
            get {
                return this.uzytkownikField;
            }
            set {
                this.uzytkownikField = value;
                this.RaisePropertyChanged("Uzytkownik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Haslo {
            get {
                return this.hasloField;
            }
            set {
                this.hasloField = value;
                this.RaisePropertyChanged("Haslo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Komunikat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDKomunikatuField;
        
        private string rodzajKomunikatuField;
        
        private string numerKomunikatuField;
        
        private string komunikat1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RodzajKomunikatu {
            get {
                return this.rodzajKomunikatuField;
            }
            set {
                this.rodzajKomunikatuField = value;
                this.RaisePropertyChanged("RodzajKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NumerKomunikatu {
            get {
                return this.numerKomunikatuField;
            }
            set {
                this.numerKomunikatuField = value;
                this.RaisePropertyChanged("NumerKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Komunikat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Komunikat1 {
            get {
                return this.komunikat1Field;
            }
            set {
                this.komunikat1Field = value;
                this.RaisePropertyChanged("Komunikat1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class StornoWplata : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string partiaPlatnosciField;
        
        private string numerPozycjiWPartiiField;
        
        private string dataKsiegowaniaField;
        
        private decimal kwotaField;
        
        private bool kwotaFieldSpecified;
        
        private string numerDokumentu1Field;
        
        private string numerDokumentu2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PartiaPlatnosci {
            get {
                return this.partiaPlatnosciField;
            }
            set {
                this.partiaPlatnosciField = value;
                this.RaisePropertyChanged("PartiaPlatnosci");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NumerPozycjiWPartii {
            get {
                return this.numerPozycjiWPartiiField;
            }
            set {
                this.numerPozycjiWPartiiField = value;
                this.RaisePropertyChanged("NumerPozycjiWPartii");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DataKsiegowania {
            get {
                return this.dataKsiegowaniaField;
            }
            set {
                this.dataKsiegowaniaField = value;
                this.RaisePropertyChanged("DataKsiegowania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal Kwota {
            get {
                return this.kwotaField;
            }
            set {
                this.kwotaField = value;
                this.RaisePropertyChanged("Kwota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KwotaSpecified {
            get {
                return this.kwotaFieldSpecified;
            }
            set {
                this.kwotaFieldSpecified = value;
                this.RaisePropertyChanged("KwotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string NumerDokumentu1 {
            get {
                return this.numerDokumentu1Field;
            }
            set {
                this.numerDokumentu1Field = value;
                this.RaisePropertyChanged("NumerDokumentu1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string NumerDokumentu2 {
            get {
                return this.numerDokumentu2Field;
            }
            set {
                this.numerDokumentu2Field = value;
                this.RaisePropertyChanged("NumerDokumentu2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Wplata : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string partiaPlatnosciField;
        
        private string numerPozycjiWPartiiField;
        
        private string numerDokumentu1Field;
        
        private string numerDokumentu2Field;
        
        private decimal kwotaCzesciowaField;
        
        private bool kwotaCzesciowaFieldSpecified;
        
        private string numerPartneraField;
        
        private string numerKontaUmowyField;
        
        private string przedmiotUmowyField;
        
        private string dataKsiegowaniaUiszczeniaField;
        
        private string dataOperacjiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PartiaPlatnosci {
            get {
                return this.partiaPlatnosciField;
            }
            set {
                this.partiaPlatnosciField = value;
                this.RaisePropertyChanged("PartiaPlatnosci");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NumerPozycjiWPartii {
            get {
                return this.numerPozycjiWPartiiField;
            }
            set {
                this.numerPozycjiWPartiiField = value;
                this.RaisePropertyChanged("NumerPozycjiWPartii");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NumerDokumentu1 {
            get {
                return this.numerDokumentu1Field;
            }
            set {
                this.numerDokumentu1Field = value;
                this.RaisePropertyChanged("NumerDokumentu1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NumerDokumentu2 {
            get {
                return this.numerDokumentu2Field;
            }
            set {
                this.numerDokumentu2Field = value;
                this.RaisePropertyChanged("NumerDokumentu2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal KwotaCzesciowa {
            get {
                return this.kwotaCzesciowaField;
            }
            set {
                this.kwotaCzesciowaField = value;
                this.RaisePropertyChanged("KwotaCzesciowa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KwotaCzesciowaSpecified {
            get {
                return this.kwotaCzesciowaFieldSpecified;
            }
            set {
                this.kwotaCzesciowaFieldSpecified = value;
                this.RaisePropertyChanged("KwotaCzesciowaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string NumerPartnera {
            get {
                return this.numerPartneraField;
            }
            set {
                this.numerPartneraField = value;
                this.RaisePropertyChanged("NumerPartnera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string NumerKontaUmowy {
            get {
                return this.numerKontaUmowyField;
            }
            set {
                this.numerKontaUmowyField = value;
                this.RaisePropertyChanged("NumerKontaUmowy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PrzedmiotUmowy {
            get {
                return this.przedmiotUmowyField;
            }
            set {
                this.przedmiotUmowyField = value;
                this.RaisePropertyChanged("PrzedmiotUmowy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string DataKsiegowaniaUiszczenia {
            get {
                return this.dataKsiegowaniaUiszczeniaField;
            }
            set {
                this.dataKsiegowaniaUiszczeniaField = value;
                this.RaisePropertyChanged("DataKsiegowaniaUiszczenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string DataOperacji {
            get {
                return this.dataOperacjiField;
            }
            set {
                this.dataOperacjiField = value;
                this.RaisePropertyChanged("DataOperacji");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Wplaty : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Wplata[] wplataField;
        
        private StornoWplata[] stornoWplataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Wplata", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Wplata[] Wplata {
            get {
                return this.wplataField;
            }
            set {
                this.wplataField = value;
                this.RaisePropertyChanged("Wplata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StornoWplata", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public StornoWplata[] StornoWplata {
            get {
                return this.stornoWplataField;
            }
            set {
                this.stornoWplataField = value;
                this.RaisePropertyChanged("StornoWplata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class PaymentClarificationsQueryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Wplaty wplatyField;
        
        private Komunikat[] komunikatyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Wplaty Wplaty {
            get {
                return this.wplatyField;
            }
            set {
                this.wplatyField = value;
                this.RaisePropertyChanged("Wplaty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Komunikat[] Komunikaty {
            get {
                return this.komunikatyField;
            }
            set {
                this.komunikatyField = value;
                this.RaisePropertyChanged("Komunikaty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentClarificationsQueryOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:PaymentClarificationsQuery", Order=0)]
        public Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryRequest PaymentClarificationsQueryRequest;
        
        public PaymentClarificationsQueryOutRequest() {
        }
        
        public PaymentClarificationsQueryOutRequest(Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryRequest PaymentClarificationsQueryRequest) {
            this.PaymentClarificationsQueryRequest = PaymentClarificationsQueryRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentClarificationsQueryOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:PaymentClarificationsQuery", Order=0)]
        public Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryResponse PaymentClarificationsQueryResponse;
        
        public PaymentClarificationsQueryOutResponse() {
        }
        
        public PaymentClarificationsQueryOutResponse(Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryResponse PaymentClarificationsQueryResponse) {
            this.PaymentClarificationsQueryResponse = PaymentClarificationsQueryResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PaymentClarificationsQueryOutChannel : Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOut, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentClarificationsQueryOutClient : System.ServiceModel.ClientBase<Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOut>, Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOut {
        
        public PaymentClarificationsQueryOutClient() {
        }
        
        public PaymentClarificationsQueryOutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentClarificationsQueryOutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentClarificationsQueryOutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentClarificationsQueryOutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOutResponse Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOut.PaymentClarificationsQueryOut(Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOutRequest request) {
            return base.Channel.PaymentClarificationsQueryOut(request);
        }
        
        public Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryResponse PaymentClarificationsQueryOut(Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryRequest PaymentClarificationsQueryRequest) {
            Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOutRequest inValue = new Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOutRequest();
            inValue.PaymentClarificationsQueryRequest = PaymentClarificationsQueryRequest;
            Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOutResponse retVal = ((Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOut)(this)).PaymentClarificationsQueryOut(inValue);
            return retVal.PaymentClarificationsQueryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOutResponse> Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOut.PaymentClarificationsQueryOutAsync(Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOutRequest request) {
            return base.Channel.PaymentClarificationsQueryOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOutResponse> PaymentClarificationsQueryOutAsync(Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryRequest PaymentClarificationsQueryRequest) {
            Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOutRequest inValue = new Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOutRequest();
            inValue.PaymentClarificationsQueryRequest = PaymentClarificationsQueryRequest;
            return ((Ex2PscdInterface.Ex2PscdPaymentClarificationsQueryOutService.PaymentClarificationsQueryOut)(this)).PaymentClarificationsQueryOutAsync(inValue);
        }
    }
}
