//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex2PscdInterface.Ex2PscdContractAccountQueryOutService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:ContractAccountQuery", ConfigurationName="Ex2PscdContractAccountQueryOutService.ContractAccountQueryOut")]
    public interface ContractAccountQueryOut {
        
        // CODEGEN: Generating message contract since the operation ContractAccountQueryOut is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOutResponse ContractAccountQueryOut(Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOutResponse> ContractAccountQueryOutAsync(Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class ContractAccountQueryRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Admin adminField;
        
        private KontoUmowyDefinicja kontoUmowyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Admin Admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
                this.RaisePropertyChanged("Admin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public KontoUmowyDefinicja KontoUmowy {
            get {
                return this.kontoUmowyField;
            }
            set {
                this.kontoUmowyField = value;
                this.RaisePropertyChanged("KontoUmowy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Admin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jednostkaGospodarczaField;
        
        private string iDKomunikatuField;
        
        private string iDSystemMerytorycznegoField;
        
        private string utworzonyDataField;
        
        private string utworzonyGodzField;
        
        private string uzytkownikField;
        
        private string hasloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string JednostkaGospodarcza {
            get {
                return this.jednostkaGospodarczaField;
            }
            set {
                this.jednostkaGospodarczaField = value;
                this.RaisePropertyChanged("JednostkaGospodarcza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IDSystemMerytorycznego {
            get {
                return this.iDSystemMerytorycznegoField;
            }
            set {
                this.iDSystemMerytorycznegoField = value;
                this.RaisePropertyChanged("IDSystemMerytorycznego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UtworzonyData {
            get {
                return this.utworzonyDataField;
            }
            set {
                this.utworzonyDataField = value;
                this.RaisePropertyChanged("UtworzonyData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string UtworzonyGodz {
            get {
                return this.utworzonyGodzField;
            }
            set {
                this.utworzonyGodzField = value;
                this.RaisePropertyChanged("UtworzonyGodz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Uzytkownik {
            get {
                return this.uzytkownikField;
            }
            set {
                this.uzytkownikField = value;
                this.RaisePropertyChanged("Uzytkownik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Haslo {
            get {
                return this.hasloField;
            }
            set {
                this.hasloField = value;
                this.RaisePropertyChanged("Haslo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Komunikat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDKomunikatuField;
        
        private string rodzajKomunikatuField;
        
        private string numerKomunikatuField;
        
        private string komunikat1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RodzajKomunikatu {
            get {
                return this.rodzajKomunikatuField;
            }
            set {
                this.rodzajKomunikatuField = value;
                this.RaisePropertyChanged("RodzajKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NumerKomunikatu {
            get {
                return this.numerKomunikatuField;
            }
            set {
                this.numerKomunikatuField = value;
                this.RaisePropertyChanged("NumerKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Komunikat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Komunikat1 {
            get {
                return this.komunikat1Field;
            }
            set {
                this.komunikat1Field = value;
                this.RaisePropertyChanged("Komunikat1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class ContractAccountQueryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private KontoUmowyDefinicja[] kontaUmowyField;
        
        private Komunikat[] komunikatyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KontoUmowy", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public KontoUmowyDefinicja[] KontaUmowy {
            get {
                return this.kontaUmowyField;
            }
            set {
                this.kontaUmowyField = value;
                this.RaisePropertyChanged("KontaUmowy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Komunikat[] Komunikaty {
            get {
                return this.komunikatyField;
            }
            set {
                this.komunikatyField = value;
                this.RaisePropertyChanged("Komunikaty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class KontoUmowyDefinicja : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numerKontaUmowyField;
        
        private string oznaczenieKontaUmowyField;
        
        private string typKontaUmowyField;
        
        private string relacjaPartneraHandlowegoField;
        
        private string numerPartneraField;
        
        private string iDPrzedmiotuUmowyField;
        
        private string jednostkaGospodarczaField;
        
        private string standardowaJednostkaGospodarczaField;
        
        private string sadFunkcjonalnyStanowiskoFinansoweField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NumerKontaUmowy {
            get {
                return this.numerKontaUmowyField;
            }
            set {
                this.numerKontaUmowyField = value;
                this.RaisePropertyChanged("NumerKontaUmowy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string OznaczenieKontaUmowy {
            get {
                return this.oznaczenieKontaUmowyField;
            }
            set {
                this.oznaczenieKontaUmowyField = value;
                this.RaisePropertyChanged("OznaczenieKontaUmowy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TypKontaUmowy {
            get {
                return this.typKontaUmowyField;
            }
            set {
                this.typKontaUmowyField = value;
                this.RaisePropertyChanged("TypKontaUmowy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string RelacjaPartneraHandlowego {
            get {
                return this.relacjaPartneraHandlowegoField;
            }
            set {
                this.relacjaPartneraHandlowegoField = value;
                this.RaisePropertyChanged("RelacjaPartneraHandlowego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string NumerPartnera {
            get {
                return this.numerPartneraField;
            }
            set {
                this.numerPartneraField = value;
                this.RaisePropertyChanged("NumerPartnera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string IDPrzedmiotuUmowy {
            get {
                return this.iDPrzedmiotuUmowyField;
            }
            set {
                this.iDPrzedmiotuUmowyField = value;
                this.RaisePropertyChanged("IDPrzedmiotuUmowy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string JednostkaGospodarcza {
            get {
                return this.jednostkaGospodarczaField;
            }
            set {
                this.jednostkaGospodarczaField = value;
                this.RaisePropertyChanged("JednostkaGospodarcza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string StandardowaJednostkaGospodarcza {
            get {
                return this.standardowaJednostkaGospodarczaField;
            }
            set {
                this.standardowaJednostkaGospodarczaField = value;
                this.RaisePropertyChanged("StandardowaJednostkaGospodarcza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SadFunkcjonalnyStanowiskoFinansowe {
            get {
                return this.sadFunkcjonalnyStanowiskoFinansoweField;
            }
            set {
                this.sadFunkcjonalnyStanowiskoFinansoweField = value;
                this.RaisePropertyChanged("SadFunkcjonalnyStanowiskoFinansowe");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContractAccountQueryOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:ContractAccountQuery", Order=0)]
        public Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryRequest ContractAccountQueryRequest;
        
        public ContractAccountQueryOutRequest() {
        }
        
        public ContractAccountQueryOutRequest(Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryRequest ContractAccountQueryRequest) {
            this.ContractAccountQueryRequest = ContractAccountQueryRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContractAccountQueryOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:ContractAccountQuery", Order=0)]
        public Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryResponse ContractAccountQueryResponse;
        
        public ContractAccountQueryOutResponse() {
        }
        
        public ContractAccountQueryOutResponse(Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryResponse ContractAccountQueryResponse) {
            this.ContractAccountQueryResponse = ContractAccountQueryResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContractAccountQueryOutChannel : Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOut, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContractAccountQueryOutClient : System.ServiceModel.ClientBase<Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOut>, Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOut {
        
        public ContractAccountQueryOutClient() {
        }
        
        public ContractAccountQueryOutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContractAccountQueryOutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractAccountQueryOutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractAccountQueryOutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOutResponse Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOut.ContractAccountQueryOut(Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOutRequest request) {
            return base.Channel.ContractAccountQueryOut(request);
        }
        
        public Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryResponse ContractAccountQueryOut(Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryRequest ContractAccountQueryRequest) {
            Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOutRequest inValue = new Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOutRequest();
            inValue.ContractAccountQueryRequest = ContractAccountQueryRequest;
            Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOutResponse retVal = ((Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOut)(this)).ContractAccountQueryOut(inValue);
            return retVal.ContractAccountQueryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOutResponse> Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOut.ContractAccountQueryOutAsync(Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOutRequest request) {
            return base.Channel.ContractAccountQueryOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOutResponse> ContractAccountQueryOutAsync(Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryRequest ContractAccountQueryRequest) {
            Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOutRequest inValue = new Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOutRequest();
            inValue.ContractAccountQueryRequest = ContractAccountQueryRequest;
            return ((Ex2PscdInterface.Ex2PscdContractAccountQueryOutService.ContractAccountQueryOut)(this)).ContractAccountQueryOutAsync(inValue);
        }
    }
}
