namespace KnsMigrator
{
    partial class SprawdzSalda
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            CheckBoxInHeader.CustomCheckBoxColumn customCheckBoxColumn1 = new CheckBoxInHeader.CustomCheckBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SprawdzSalda));
            this.rgvKsiegi = new Telerik.WinControls.UI.RadGridView();
            this.rdtDzien = new Telerik.WinControls.UI.RadDateTimePicker();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.btSrc = new System.Windows.Forms.Button();
            this.tbInput = new System.Windows.Forms.TextBox();
            this.btRun = new System.Windows.Forms.Button();
            this.tbMess = new System.Windows.Forms.TextBox();
            this.tbPos = new System.Windows.Forms.TextBox();
            ((System.ComponentModel.ISupportInitialize)(this.rgvKsiegi)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.rdtDzien)).BeginInit();
            this.SuspendLayout();
            // 
            // rgvKsiegi
            // 
            this.rgvKsiegi.Location = new System.Drawing.Point(12, 58);
            // 
            // rgvKsiegi
            // 
            this.rgvKsiegi.MasterTemplate.AllowAddNewRow = false;
            this.rgvKsiegi.MasterTemplate.AllowColumnReorder = false;
            this.rgvKsiegi.MasterTemplate.AutoGenerateColumns = false;
            customCheckBoxColumn1.AllowSort = false;
            customCheckBoxColumn1.HeaderText = "";
            customCheckBoxColumn1.Name = "taknie";
            gridViewTextBoxColumn1.FieldName = "nazwa";
            gridViewTextBoxColumn1.HeaderText = "Księga należności";
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.Name = "nazwa";
            gridViewTextBoxColumn1.ReadOnly = true;
            gridViewTextBoxColumn1.Width = 400;
            gridViewDecimalColumn1.DataType = typeof(System.Nullable<int>);
            gridViewDecimalColumn1.FieldName = "Id_Ksiegi";
            gridViewDecimalColumn1.HeaderText = "Id_Ksiegi";
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.IsVisible = false;
            gridViewDecimalColumn1.Name = "Id_Ksiegi";
            this.rgvKsiegi.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            customCheckBoxColumn1,
            gridViewTextBoxColumn1,
            gridViewDecimalColumn1});
            this.rgvKsiegi.Name = "rgvKsiegi";
            this.rgvKsiegi.ShowGroupPanel = false;
            this.rgvKsiegi.Size = new System.Drawing.Size(487, 290);
            this.rgvKsiegi.TabIndex = 10;
            this.rgvKsiegi.Text = "rgvKsiegi";
            // 
            // rdtDzien
            // 
            this.rdtDzien.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(238)));
            this.rdtDzien.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.rdtDzien.Location = new System.Drawing.Point(118, 5);
            this.rdtDzien.Name = "rdtDzien";
            this.rdtDzien.Size = new System.Drawing.Size(93, 23);
            this.rdtDzien.TabIndex = 11;
            this.rdtDzien.TabStop = false;
            this.rdtDzien.Text = "2014-01-13";
            this.rdtDzien.Value = new System.DateTime(2014, 1, 13, 12, 28, 2, 762);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(238)));
            this.label1.Location = new System.Drawing.Point(13, 12);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(100, 16);
            this.label1.TabIndex = 12;
            this.label1.Text = "Salda na dzień:";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(238)));
            this.label2.Location = new System.Drawing.Point(13, 39);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(173, 16);
            this.label2.TabIndex = 13;
            this.label2.Text = "Wybierz księgi do walidacji:";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(238)));
            this.label3.Location = new System.Drawing.Point(22, 366);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(189, 16);
            this.label3.TabIndex = 14;
            this.label3.Text = "Raport z RUP  (ZPSCDDOKS):";
            // 
            // btSrc
            // 
            this.btSrc.Location = new System.Drawing.Point(464, 382);
            this.btSrc.Name = "btSrc";
            this.btSrc.Size = new System.Drawing.Size(28, 23);
            this.btSrc.TabIndex = 16;
            this.btSrc.Text = "...";
            this.btSrc.UseVisualStyleBackColor = true;
            this.btSrc.Click += new System.EventHandler(this.btSrc_Click);
            // 
            // tbInput
            // 
            this.tbInput.Location = new System.Drawing.Point(16, 385);
            this.tbInput.Name = "tbInput";
            this.tbInput.Size = new System.Drawing.Size(442, 20);
            this.tbInput.TabIndex = 15;
            // 
            // btRun
            // 
            this.btRun.Location = new System.Drawing.Point(201, 428);
            this.btRun.Name = "btRun";
            this.btRun.Size = new System.Drawing.Size(87, 23);
            this.btRun.TabIndex = 17;
            this.btRun.Text = "Uruchom";
            this.btRun.UseVisualStyleBackColor = true;
            this.btRun.Click += new System.EventHandler(this.btRun_Click);
            // 
            // tbMess
            // 
            this.tbMess.Enabled = false;
            this.tbMess.Location = new System.Drawing.Point(224, 8);
            this.tbMess.Name = "tbMess";
            this.tbMess.Size = new System.Drawing.Size(275, 20);
            this.tbMess.TabIndex = 18;
            // 
            // tbPos
            // 
            this.tbPos.Enabled = false;
            this.tbPos.Location = new System.Drawing.Point(224, 34);
            this.tbPos.Name = "tbPos";
            this.tbPos.Size = new System.Drawing.Size(81, 20);
            this.tbPos.TabIndex = 19;
            // 
            // SprawdzSalda
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(504, 463);
            this.Controls.Add(this.tbPos);
            this.Controls.Add(this.tbMess);
            this.Controls.Add(this.btRun);
            this.Controls.Add(this.btSrc);
            this.Controls.Add(this.tbInput);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.rdtDzien);
            this.Controls.Add(this.rgvKsiegi);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "SprawdzSalda";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Walidacja Sald";
            this.Load += new System.EventHandler(this.SprawdzSalda_Load);
            ((System.ComponentModel.ISupportInitialize)(this.rgvKsiegi)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.rdtDzien)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Telerik.WinControls.UI.RadGridView rgvKsiegi;
        private Telerik.WinControls.UI.RadDateTimePicker rdtDzien;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Button btSrc;
        private System.Windows.Forms.TextBox tbInput;
        private System.Windows.Forms.Button btRun;
        private System.Windows.Forms.TextBox tbMess;
        private System.Windows.Forms.TextBox tbPos;
    }
}