//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RupDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RupDBEntities : DbContext
    {
        public RupDBEntities()
            : base("name=RupDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Konfiguracja> Konfiguracja { get; set; }
        public DbSet<ServiceEndpoint> ServiceEndpoint { get; set; }
        public DbSet<ConsExternalDBConnectionConfig> ConsExternalDBConnectionConfig { get; set; }
        public DbSet<ConsJobItem> ConsJobItem { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<ConsKartaTransfer> ConsKartaTransfer { get; set; }
    }
}
