//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RupDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Pssword { get; set; }
        public int role { get; set; }
        public Nullable<System.DateTime> LastPwdChngDate { get; set; }
        public Nullable<bool> suspend { get; set; }
        public Nullable<bool> ChangePwd { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public int PwdPeriodChange { get; set; }
        public string MEPUser { get; set; }
        public string MEPPassword { get; set; }
    }
}
