//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex2PscdInterface.Ex2PscdDocumentCreateOutService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:DocumentCreate", ConfigurationName="Ex2PscdDocumentCreateOutService.DocumentCreateOut")]
    public interface DocumentCreateOut {
        
        // CODEGEN: Generating message contract since the operation DocumentCreateOut is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOutResponse DocumentCreateOut(Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOutResponse> DocumentCreateOutAsync(Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class DocumentCreateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Admin adminField;
        
        private NaglowekDokument naglowekDokumentField;
        
        private PozycjaDokumentuPH pozycjaDokumentPHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Admin Admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
                this.RaisePropertyChanged("Admin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public NaglowekDokument NaglowekDokument {
            get {
                return this.naglowekDokumentField;
            }
            set {
                this.naglowekDokumentField = value;
                this.RaisePropertyChanged("NaglowekDokument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public PozycjaDokumentuPH PozycjaDokumentPH {
            get {
                return this.pozycjaDokumentPHField;
            }
            set {
                this.pozycjaDokumentPHField = value;
                this.RaisePropertyChanged("PozycjaDokumentPH");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Admin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jednostkaGospodarczaField;
        
        private string iDKomunikatuField;
        
        private string iDSystemMerytorycznegoField;
        
        private string utworzonyDataField;
        
        private string utworzonyGodzField;
        
        private string uzytkownikField;
        
        private string hasloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string JednostkaGospodarcza {
            get {
                return this.jednostkaGospodarczaField;
            }
            set {
                this.jednostkaGospodarczaField = value;
                this.RaisePropertyChanged("JednostkaGospodarcza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IDSystemMerytorycznego {
            get {
                return this.iDSystemMerytorycznegoField;
            }
            set {
                this.iDSystemMerytorycznegoField = value;
                this.RaisePropertyChanged("IDSystemMerytorycznego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UtworzonyData {
            get {
                return this.utworzonyDataField;
            }
            set {
                this.utworzonyDataField = value;
                this.RaisePropertyChanged("UtworzonyData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string UtworzonyGodz {
            get {
                return this.utworzonyGodzField;
            }
            set {
                this.utworzonyGodzField = value;
                this.RaisePropertyChanged("UtworzonyGodz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Uzytkownik {
            get {
                return this.uzytkownikField;
            }
            set {
                this.uzytkownikField = value;
                this.RaisePropertyChanged("Uzytkownik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Haslo {
            get {
                return this.hasloField;
            }
            set {
                this.hasloField = value;
                this.RaisePropertyChanged("Haslo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Komunikat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDKomunikatuField;
        
        private string rodzajKomunikatuField;
        
        private string numerKomunikatuField;
        
        private string komunikat1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RodzajKomunikatu {
            get {
                return this.rodzajKomunikatuField;
            }
            set {
                this.rodzajKomunikatuField = value;
                this.RaisePropertyChanged("RodzajKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NumerKomunikatu {
            get {
                return this.numerKomunikatuField;
            }
            set {
                this.numerKomunikatuField = value;
                this.RaisePropertyChanged("NumerKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Komunikat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Komunikat1 {
            get {
                return this.komunikat1Field;
            }
            set {
                this.komunikat1Field = value;
                this.RaisePropertyChanged("Komunikat1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class IdDanePSCD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jednostkaGospodarczaField;
        
        private string iDPartnerField;
        
        private string iDKontoUmowyField;
        
        private string iDSygnaturaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string JednostkaGospodarcza {
            get {
                return this.jednostkaGospodarczaField;
            }
            set {
                this.jednostkaGospodarczaField = value;
                this.RaisePropertyChanged("JednostkaGospodarcza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IDPartner {
            get {
                return this.iDPartnerField;
            }
            set {
                this.iDPartnerField = value;
                this.RaisePropertyChanged("IDPartner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IDKontoUmowy {
            get {
                return this.iDKontoUmowyField;
            }
            set {
                this.iDKontoUmowyField = value;
                this.RaisePropertyChanged("IDKontoUmowy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IDSygnatura {
            get {
                return this.iDSygnaturaField;
            }
            set {
                this.iDSygnaturaField = value;
                this.RaisePropertyChanged("IDSygnatura");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class DocumentCreateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDDokumentField;
        
        private IdDanePSCD idDanePSCDField;
        
        private Komunikat[] komunikatyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDDokument {
            get {
                return this.iDDokumentField;
            }
            set {
                this.iDDokumentField = value;
                this.RaisePropertyChanged("IDDokument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public IdDanePSCD IdDanePSCD {
            get {
                return this.idDanePSCDField;
            }
            set {
                this.idDanePSCDField = value;
                this.RaisePropertyChanged("IdDanePSCD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Komunikat[] Komunikaty {
            get {
                return this.komunikatyField;
            }
            set {
                this.komunikatyField = value;
                this.RaisePropertyChanged("Komunikaty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class RachunekBankowy : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string krajField;
        
        private string numerBankuField;
        
        private string kontoBankoweField;
        
        private string kodKontrolnyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Kraj {
            get {
                return this.krajField;
            }
            set {
                this.krajField = value;
                this.RaisePropertyChanged("Kraj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NumerBanku {
            get {
                return this.numerBankuField;
            }
            set {
                this.numerBankuField = value;
                this.RaisePropertyChanged("NumerBanku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string KontoBankowe {
            get {
                return this.kontoBankoweField;
            }
            set {
                this.kontoBankoweField = value;
                this.RaisePropertyChanged("KontoBankowe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string KodKontrolny {
            get {
                return this.kodKontrolnyField;
            }
            set {
                this.kodKontrolnyField = value;
                this.RaisePropertyChanged("KodKontrolny");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class PozycjaDokumentuPH : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jednostkaGospodarczaField;
        
        private string iDPartnerField;
        
        private string iDKontoUmowyField;
        
        private string iDSygnaturaField;
        
        private string operacjaGlField;
        
        private string operacjaCzField;
        
        private string kwotaField;
        
        private string dataPlatnosciField;
        
        private string tekstField;
        
        private string formaPlatnosciField;
        
        private string iDOdbiorcaPlatnosciField;
        
        private RachunekBankowy rachunekBankowyOdbiorcaPlatnosciField;
        
        private RachunekBankowy rachunekBankowyPartnerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string JednostkaGospodarcza {
            get {
                return this.jednostkaGospodarczaField;
            }
            set {
                this.jednostkaGospodarczaField = value;
                this.RaisePropertyChanged("JednostkaGospodarcza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IDPartner {
            get {
                return this.iDPartnerField;
            }
            set {
                this.iDPartnerField = value;
                this.RaisePropertyChanged("IDPartner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IDKontoUmowy {
            get {
                return this.iDKontoUmowyField;
            }
            set {
                this.iDKontoUmowyField = value;
                this.RaisePropertyChanged("IDKontoUmowy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IDSygnatura {
            get {
                return this.iDSygnaturaField;
            }
            set {
                this.iDSygnaturaField = value;
                this.RaisePropertyChanged("IDSygnatura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string OperacjaGl {
            get {
                return this.operacjaGlField;
            }
            set {
                this.operacjaGlField = value;
                this.RaisePropertyChanged("OperacjaGl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string OperacjaCz {
            get {
                return this.operacjaCzField;
            }
            set {
                this.operacjaCzField = value;
                this.RaisePropertyChanged("OperacjaCz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Kwota {
            get {
                return this.kwotaField;
            }
            set {
                this.kwotaField = value;
                this.RaisePropertyChanged("Kwota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string DataPlatnosci {
            get {
                return this.dataPlatnosciField;
            }
            set {
                this.dataPlatnosciField = value;
                this.RaisePropertyChanged("DataPlatnosci");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Tekst {
            get {
                return this.tekstField;
            }
            set {
                this.tekstField = value;
                this.RaisePropertyChanged("Tekst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string FormaPlatnosci {
            get {
                return this.formaPlatnosciField;
            }
            set {
                this.formaPlatnosciField = value;
                this.RaisePropertyChanged("FormaPlatnosci");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string IDOdbiorcaPlatnosci {
            get {
                return this.iDOdbiorcaPlatnosciField;
            }
            set {
                this.iDOdbiorcaPlatnosciField = value;
                this.RaisePropertyChanged("IDOdbiorcaPlatnosci");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public RachunekBankowy RachunekBankowyOdbiorcaPlatnosci {
            get {
                return this.rachunekBankowyOdbiorcaPlatnosciField;
            }
            set {
                this.rachunekBankowyOdbiorcaPlatnosciField = value;
                this.RaisePropertyChanged("RachunekBankowyOdbiorcaPlatnosci");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public RachunekBankowy RachunekBankowyPartner {
            get {
                return this.rachunekBankowyPartnerField;
            }
            set {
                this.rachunekBankowyPartnerField = value;
                this.RaisePropertyChanged("RachunekBankowyPartner");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class NaglowekDokument : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numerDokumentuField;
        
        private string rodzajDokumentuField;
        
        private string dataDokumentField;
        
        private string dataKsiegowanieField;
        
        private string dataOperacjiField;
        
        private string walutaField;
        
        private string referencjaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NumerDokumentu {
            get {
                return this.numerDokumentuField;
            }
            set {
                this.numerDokumentuField = value;
                this.RaisePropertyChanged("NumerDokumentu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RodzajDokumentu {
            get {
                return this.rodzajDokumentuField;
            }
            set {
                this.rodzajDokumentuField = value;
                this.RaisePropertyChanged("RodzajDokumentu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DataDokument {
            get {
                return this.dataDokumentField;
            }
            set {
                this.dataDokumentField = value;
                this.RaisePropertyChanged("DataDokument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DataKsiegowanie {
            get {
                return this.dataKsiegowanieField;
            }
            set {
                this.dataKsiegowanieField = value;
                this.RaisePropertyChanged("DataKsiegowanie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DataOperacji {
            get {
                return this.dataOperacjiField;
            }
            set {
                this.dataOperacjiField = value;
                this.RaisePropertyChanged("DataOperacji");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Waluta {
            get {
                return this.walutaField;
            }
            set {
                this.walutaField = value;
                this.RaisePropertyChanged("Waluta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Referencja {
            get {
                return this.referencjaField;
            }
            set {
                this.referencjaField = value;
                this.RaisePropertyChanged("Referencja");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocumentCreateOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:DocumentCreate", Order=0)]
        public Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateRequest DocumentCreateRequest;
        
        public DocumentCreateOutRequest() {
        }
        
        public DocumentCreateOutRequest(Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateRequest DocumentCreateRequest) {
            this.DocumentCreateRequest = DocumentCreateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocumentCreateOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:DocumentCreate", Order=0)]
        public Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateResponse DocumentCreateResponse;
        
        public DocumentCreateOutResponse() {
        }
        
        public DocumentCreateOutResponse(Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateResponse DocumentCreateResponse) {
            this.DocumentCreateResponse = DocumentCreateResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocumentCreateOutChannel : Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOut, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentCreateOutClient : System.ServiceModel.ClientBase<Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOut>, Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOut {
        
        public DocumentCreateOutClient() {
        }
        
        public DocumentCreateOutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentCreateOutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentCreateOutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentCreateOutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOutResponse Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOut.DocumentCreateOut(Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOutRequest request) {
            return base.Channel.DocumentCreateOut(request);
        }
        
        public Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateResponse DocumentCreateOut(Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateRequest DocumentCreateRequest) {
            Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOutRequest inValue = new Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOutRequest();
            inValue.DocumentCreateRequest = DocumentCreateRequest;
            Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOutResponse retVal = ((Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOut)(this)).DocumentCreateOut(inValue);
            return retVal.DocumentCreateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOutResponse> Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOut.DocumentCreateOutAsync(Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOutRequest request) {
            return base.Channel.DocumentCreateOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOutResponse> DocumentCreateOutAsync(Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateRequest DocumentCreateRequest) {
            Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOutRequest inValue = new Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOutRequest();
            inValue.DocumentCreateRequest = DocumentCreateRequest;
            return ((Ex2PscdInterface.Ex2PscdDocumentCreateOutService.DocumentCreateOut)(this)).DocumentCreateOutAsync(inValue);
        }
    }
}
