//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex2PscdInterface.Ex2PscdContractObjectCreateOutService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:ContractObjectCreate", ConfigurationName="Ex2PscdContractObjectCreateOutService.ContractObjectCreateOut")]
    public interface ContractObjectCreateOut {
        
        // CODEGEN: Generating message contract since the operation ContractObjectCreateOut is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOutResponse ContractObjectCreateOut(Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOutResponse> ContractObjectCreateOutAsync(Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class ContractObjectCreateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Admin adminField;
        
        private SygnaturaTworzenie sygnaturaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Admin Admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
                this.RaisePropertyChanged("Admin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public SygnaturaTworzenie Sygnatura {
            get {
                return this.sygnaturaField;
            }
            set {
                this.sygnaturaField = value;
                this.RaisePropertyChanged("Sygnatura");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Admin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jednostkaGospodarczaField;
        
        private string iDKomunikatuField;
        
        private string iDSystemMerytorycznegoField;
        
        private string utworzonyDataField;
        
        private string utworzonyGodzField;
        
        private string uzytkownikField;
        
        private string hasloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string JednostkaGospodarcza {
            get {
                return this.jednostkaGospodarczaField;
            }
            set {
                this.jednostkaGospodarczaField = value;
                this.RaisePropertyChanged("JednostkaGospodarcza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IDSystemMerytorycznego {
            get {
                return this.iDSystemMerytorycznegoField;
            }
            set {
                this.iDSystemMerytorycznegoField = value;
                this.RaisePropertyChanged("IDSystemMerytorycznego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UtworzonyData {
            get {
                return this.utworzonyDataField;
            }
            set {
                this.utworzonyDataField = value;
                this.RaisePropertyChanged("UtworzonyData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string UtworzonyGodz {
            get {
                return this.utworzonyGodzField;
            }
            set {
                this.utworzonyGodzField = value;
                this.RaisePropertyChanged("UtworzonyGodz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Uzytkownik {
            get {
                return this.uzytkownikField;
            }
            set {
                this.uzytkownikField = value;
                this.RaisePropertyChanged("Uzytkownik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Haslo {
            get {
                return this.hasloField;
            }
            set {
                this.hasloField = value;
                this.RaisePropertyChanged("Haslo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Komunikat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDKomunikatuField;
        
        private string rodzajKomunikatuField;
        
        private string numerKomunikatuField;
        
        private string komunikat1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RodzajKomunikatu {
            get {
                return this.rodzajKomunikatuField;
            }
            set {
                this.rodzajKomunikatuField = value;
                this.RaisePropertyChanged("RodzajKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NumerKomunikatu {
            get {
                return this.numerKomunikatuField;
            }
            set {
                this.numerKomunikatuField = value;
                this.RaisePropertyChanged("NumerKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Komunikat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Komunikat1 {
            get {
                return this.komunikat1Field;
            }
            set {
                this.komunikat1Field = value;
                this.RaisePropertyChanged("Komunikat1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class SygnaturaIdentyfikacja : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDPrzedmiotuUmowyField;
        
        private string oznaczeniePrzedmiotuUmowyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDPrzedmiotuUmowy {
            get {
                return this.iDPrzedmiotuUmowyField;
            }
            set {
                this.iDPrzedmiotuUmowyField = value;
                this.RaisePropertyChanged("IDPrzedmiotuUmowy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string OznaczeniePrzedmiotuUmowy {
            get {
                return this.oznaczeniePrzedmiotuUmowyField;
            }
            set {
                this.oznaczeniePrzedmiotuUmowyField = value;
                this.RaisePropertyChanged("OznaczeniePrzedmiotuUmowy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class ContractObjectCreateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SygnaturaIdentyfikacja sygnaturaField;
        
        private Komunikat[] komunikatyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public SygnaturaIdentyfikacja Sygnatura {
            get {
                return this.sygnaturaField;
            }
            set {
                this.sygnaturaField = value;
                this.RaisePropertyChanged("Sygnatura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Komunikat[] Komunikaty {
            get {
                return this.komunikatyField;
            }
            set {
                this.komunikatyField = value;
                this.RaisePropertyChanged("Komunikaty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class SygnaturaTworzenie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rodzajPrzedmiotuUmowyField;
        
        private string jednostkaGospodarczaField;
        
        private string numerWydzialuISekcjiField;
        
        private string repertoriumField;
        
        private string kolejnyNumerSprawyField;
        
        private string rokField;
        
        private string rodzajSprawyField;
        
        private string iloscTomowField;
        
        private string podrodzajSprawyField;
        
        private string sadFunkcjonalnyStanowiskoFinansoweField;
        
        private string daneDoWindykacjiJednostkaGospodarczaField;
        
        private string daneDoWindykacjiSadFunkcjonalnyStanowiskoFinansoweField;
        
        private string rerfencjaArchField;
        
        private string jednostkaGospodarczaArchField;
        
        private string stanowiskoFinansoweArchField;
        
        private string numeWydzISekcjiArchField;
        
        private string repertoriumArchField;
        
        private string kolenyNumerSprawyArchField;
        
        private string rokArchField;
        
        private string kodOkreguKWField;
        
        private string kontrolkaSygnaturyKWField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RodzajPrzedmiotuUmowy {
            get {
                return this.rodzajPrzedmiotuUmowyField;
            }
            set {
                this.rodzajPrzedmiotuUmowyField = value;
                this.RaisePropertyChanged("RodzajPrzedmiotuUmowy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string JednostkaGospodarcza {
            get {
                return this.jednostkaGospodarczaField;
            }
            set {
                this.jednostkaGospodarczaField = value;
                this.RaisePropertyChanged("JednostkaGospodarcza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NumerWydzialuISekcji {
            get {
                return this.numerWydzialuISekcjiField;
            }
            set {
                this.numerWydzialuISekcjiField = value;
                this.RaisePropertyChanged("NumerWydzialuISekcji");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Repertorium {
            get {
                return this.repertoriumField;
            }
            set {
                this.repertoriumField = value;
                this.RaisePropertyChanged("Repertorium");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string KolejnyNumerSprawy {
            get {
                return this.kolejnyNumerSprawyField;
            }
            set {
                this.kolejnyNumerSprawyField = value;
                this.RaisePropertyChanged("KolejnyNumerSprawy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Rok {
            get {
                return this.rokField;
            }
            set {
                this.rokField = value;
                this.RaisePropertyChanged("Rok");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string RodzajSprawy {
            get {
                return this.rodzajSprawyField;
            }
            set {
                this.rodzajSprawyField = value;
                this.RaisePropertyChanged("RodzajSprawy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string IloscTomow {
            get {
                return this.iloscTomowField;
            }
            set {
                this.iloscTomowField = value;
                this.RaisePropertyChanged("IloscTomow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string PodrodzajSprawy {
            get {
                return this.podrodzajSprawyField;
            }
            set {
                this.podrodzajSprawyField = value;
                this.RaisePropertyChanged("PodrodzajSprawy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string SadFunkcjonalnyStanowiskoFinansowe {
            get {
                return this.sadFunkcjonalnyStanowiskoFinansoweField;
            }
            set {
                this.sadFunkcjonalnyStanowiskoFinansoweField = value;
                this.RaisePropertyChanged("SadFunkcjonalnyStanowiskoFinansowe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string DaneDoWindykacjiJednostkaGospodarcza {
            get {
                return this.daneDoWindykacjiJednostkaGospodarczaField;
            }
            set {
                this.daneDoWindykacjiJednostkaGospodarczaField = value;
                this.RaisePropertyChanged("DaneDoWindykacjiJednostkaGospodarcza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string DaneDoWindykacjiSadFunkcjonalnyStanowiskoFinansowe {
            get {
                return this.daneDoWindykacjiSadFunkcjonalnyStanowiskoFinansoweField;
            }
            set {
                this.daneDoWindykacjiSadFunkcjonalnyStanowiskoFinansoweField = value;
                this.RaisePropertyChanged("DaneDoWindykacjiSadFunkcjonalnyStanowiskoFinansowe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string RerfencjaArch {
            get {
                return this.rerfencjaArchField;
            }
            set {
                this.rerfencjaArchField = value;
                this.RaisePropertyChanged("RerfencjaArch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string JednostkaGospodarczaArch {
            get {
                return this.jednostkaGospodarczaArchField;
            }
            set {
                this.jednostkaGospodarczaArchField = value;
                this.RaisePropertyChanged("JednostkaGospodarczaArch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string StanowiskoFinansoweArch {
            get {
                return this.stanowiskoFinansoweArchField;
            }
            set {
                this.stanowiskoFinansoweArchField = value;
                this.RaisePropertyChanged("StanowiskoFinansoweArch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string NumeWydzISekcjiArch {
            get {
                return this.numeWydzISekcjiArchField;
            }
            set {
                this.numeWydzISekcjiArchField = value;
                this.RaisePropertyChanged("NumeWydzISekcjiArch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string RepertoriumArch {
            get {
                return this.repertoriumArchField;
            }
            set {
                this.repertoriumArchField = value;
                this.RaisePropertyChanged("RepertoriumArch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string KolenyNumerSprawyArch {
            get {
                return this.kolenyNumerSprawyArchField;
            }
            set {
                this.kolenyNumerSprawyArchField = value;
                this.RaisePropertyChanged("KolenyNumerSprawyArch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string RokArch {
            get {
                return this.rokArchField;
            }
            set {
                this.rokArchField = value;
                this.RaisePropertyChanged("RokArch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string KodOkreguKW {
            get {
                return this.kodOkreguKWField;
            }
            set {
                this.kodOkreguKWField = value;
                this.RaisePropertyChanged("KodOkreguKW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string KontrolkaSygnaturyKW {
            get {
                return this.kontrolkaSygnaturyKWField;
            }
            set {
                this.kontrolkaSygnaturyKWField = value;
                this.RaisePropertyChanged("KontrolkaSygnaturyKW");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContractObjectCreateOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:ContractObjectCreate", Order=0)]
        public Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateRequest ContractObjectCreateRequest;
        
        public ContractObjectCreateOutRequest() {
        }
        
        public ContractObjectCreateOutRequest(Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateRequest ContractObjectCreateRequest) {
            this.ContractObjectCreateRequest = ContractObjectCreateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContractObjectCreateOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:ContractObjectCreate", Order=0)]
        public Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateResponse ContractObjectCreateResponse;
        
        public ContractObjectCreateOutResponse() {
        }
        
        public ContractObjectCreateOutResponse(Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateResponse ContractObjectCreateResponse) {
            this.ContractObjectCreateResponse = ContractObjectCreateResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContractObjectCreateOutChannel : Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOut, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContractObjectCreateOutClient : System.ServiceModel.ClientBase<Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOut>, Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOut {
        
        public ContractObjectCreateOutClient() {
        }
        
        public ContractObjectCreateOutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContractObjectCreateOutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractObjectCreateOutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractObjectCreateOutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOutResponse Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOut.ContractObjectCreateOut(Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOutRequest request) {
            return base.Channel.ContractObjectCreateOut(request);
        }
        
        public Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateResponse ContractObjectCreateOut(Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateRequest ContractObjectCreateRequest) {
            Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOutRequest inValue = new Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOutRequest();
            inValue.ContractObjectCreateRequest = ContractObjectCreateRequest;
            Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOutResponse retVal = ((Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOut)(this)).ContractObjectCreateOut(inValue);
            return retVal.ContractObjectCreateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOutResponse> Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOut.ContractObjectCreateOutAsync(Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOutRequest request) {
            return base.Channel.ContractObjectCreateOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOutResponse> ContractObjectCreateOutAsync(Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateRequest ContractObjectCreateRequest) {
            Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOutRequest inValue = new Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOutRequest();
            inValue.ContractObjectCreateRequest = ContractObjectCreateRequest;
            return ((Ex2PscdInterface.Ex2PscdContractObjectCreateOutService.ContractObjectCreateOut)(this)).ContractObjectCreateOutAsync(inValue);
        }
    }
}
