//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:PaymentClarificationZDOBCreate", ConfigurationName="Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOut" +
        "")]
    public interface PaymentClarificationZDOBCreateOut {
        
        // CODEGEN: Generating message contract since the operation PaymentClarificationZDOBCreateOut is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOutResponse PaymentClarificationZDOBCreateOut(Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOutResponse> PaymentClarificationZDOBCreateOutAsync(Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class PaymentClarificationZDOBCreateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Admin adminField;
        
        private PozycjaDoRozliczeniaZDOB pozycjaDoRozliczeniaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Admin Admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
                this.RaisePropertyChanged("Admin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public PozycjaDoRozliczeniaZDOB PozycjaDoRozliczenia {
            get {
                return this.pozycjaDoRozliczeniaField;
            }
            set {
                this.pozycjaDoRozliczeniaField = value;
                this.RaisePropertyChanged("PozycjaDoRozliczenia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Admin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jednostkaGospodarczaField;
        
        private string iDKomunikatuField;
        
        private string iDSystemMerytorycznegoField;
        
        private string utworzonyDataField;
        
        private string utworzonyGodzField;
        
        private string uzytkownikField;
        
        private string hasloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string JednostkaGospodarcza {
            get {
                return this.jednostkaGospodarczaField;
            }
            set {
                this.jednostkaGospodarczaField = value;
                this.RaisePropertyChanged("JednostkaGospodarcza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IDSystemMerytorycznego {
            get {
                return this.iDSystemMerytorycznegoField;
            }
            set {
                this.iDSystemMerytorycznegoField = value;
                this.RaisePropertyChanged("IDSystemMerytorycznego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UtworzonyData {
            get {
                return this.utworzonyDataField;
            }
            set {
                this.utworzonyDataField = value;
                this.RaisePropertyChanged("UtworzonyData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string UtworzonyGodz {
            get {
                return this.utworzonyGodzField;
            }
            set {
                this.utworzonyGodzField = value;
                this.RaisePropertyChanged("UtworzonyGodz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Uzytkownik {
            get {
                return this.uzytkownikField;
            }
            set {
                this.uzytkownikField = value;
                this.RaisePropertyChanged("Uzytkownik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Haslo {
            get {
                return this.hasloField;
            }
            set {
                this.hasloField = value;
                this.RaisePropertyChanged("Haslo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Komunikat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDKomunikatuField;
        
        private string rodzajKomunikatuField;
        
        private string numerKomunikatuField;
        
        private string komunikat1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RodzajKomunikatu {
            get {
                return this.rodzajKomunikatuField;
            }
            set {
                this.rodzajKomunikatuField = value;
                this.RaisePropertyChanged("RodzajKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NumerKomunikatu {
            get {
                return this.numerKomunikatuField;
            }
            set {
                this.numerKomunikatuField = value;
                this.RaisePropertyChanged("NumerKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Komunikat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Komunikat1 {
            get {
                return this.komunikat1Field;
            }
            set {
                this.komunikat1Field = value;
                this.RaisePropertyChanged("Komunikat1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class PaymentClarificationZDOBCreateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iD_WyjasnieniaField;
        
        private Komunikat[] komunikatyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID_Wyjasnienia {
            get {
                return this.iD_WyjasnieniaField;
            }
            set {
                this.iD_WyjasnieniaField = value;
                this.RaisePropertyChanged("ID_Wyjasnienia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Komunikat[] Komunikaty {
            get {
                return this.komunikatyField;
            }
            set {
                this.komunikatyField = value;
                this.RaisePropertyChanged("Komunikaty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class PozycjaPlatnosci : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string partiaPlatnosciIDField;
        
        private string partiaPlatnosciNrPozycjaField;
        
        private string jednostkaGospodarczaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PartiaPlatnosciID {
            get {
                return this.partiaPlatnosciIDField;
            }
            set {
                this.partiaPlatnosciIDField = value;
                this.RaisePropertyChanged("PartiaPlatnosciID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PartiaPlatnosciNrPozycja {
            get {
                return this.partiaPlatnosciNrPozycjaField;
            }
            set {
                this.partiaPlatnosciNrPozycjaField = value;
                this.RaisePropertyChanged("PartiaPlatnosciNrPozycja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string JednostkaGospodarcza {
            get {
                return this.jednostkaGospodarczaField;
            }
            set {
                this.jednostkaGospodarczaField = value;
                this.RaisePropertyChanged("JednostkaGospodarcza");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class PozycjaDoRozliczeniaZDOB : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PozycjaPlatnosci pozycjaPlatnosciField;
        
        private string kwotaField;
        
        private string numerDokumentuField;
        
        private string dataDokumentuField;
        
        private string dataKsiegowaniaField;
        
        private string iDPartnerField;
        
        private string iDKontoUmowyField;
        
        private string iDSygnaturaField;
        
        private string operacjaGlField;
        
        private string operacjaCzField;
        
        private string dodTekstDoKsField;
        
        private string numerDokZalKomField;
        
        private string numerDokRefField;
        
        private string numerDokBaliField;
        
        private string dodDaneWybField;
        
        private string inicjalySedziegoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PozycjaPlatnosci PozycjaPlatnosci {
            get {
                return this.pozycjaPlatnosciField;
            }
            set {
                this.pozycjaPlatnosciField = value;
                this.RaisePropertyChanged("PozycjaPlatnosci");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Kwota {
            get {
                return this.kwotaField;
            }
            set {
                this.kwotaField = value;
                this.RaisePropertyChanged("Kwota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NumerDokumentu {
            get {
                return this.numerDokumentuField;
            }
            set {
                this.numerDokumentuField = value;
                this.RaisePropertyChanged("NumerDokumentu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DataDokumentu {
            get {
                return this.dataDokumentuField;
            }
            set {
                this.dataDokumentuField = value;
                this.RaisePropertyChanged("DataDokumentu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DataKsiegowania {
            get {
                return this.dataKsiegowaniaField;
            }
            set {
                this.dataKsiegowaniaField = value;
                this.RaisePropertyChanged("DataKsiegowania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string IDPartner {
            get {
                return this.iDPartnerField;
            }
            set {
                this.iDPartnerField = value;
                this.RaisePropertyChanged("IDPartner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string IDKontoUmowy {
            get {
                return this.iDKontoUmowyField;
            }
            set {
                this.iDKontoUmowyField = value;
                this.RaisePropertyChanged("IDKontoUmowy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string IDSygnatura {
            get {
                return this.iDSygnaturaField;
            }
            set {
                this.iDSygnaturaField = value;
                this.RaisePropertyChanged("IDSygnatura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string OperacjaGl {
            get {
                return this.operacjaGlField;
            }
            set {
                this.operacjaGlField = value;
                this.RaisePropertyChanged("OperacjaGl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string OperacjaCz {
            get {
                return this.operacjaCzField;
            }
            set {
                this.operacjaCzField = value;
                this.RaisePropertyChanged("OperacjaCz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string DodTekstDoKs {
            get {
                return this.dodTekstDoKsField;
            }
            set {
                this.dodTekstDoKsField = value;
                this.RaisePropertyChanged("DodTekstDoKs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string NumerDokZalKom {
            get {
                return this.numerDokZalKomField;
            }
            set {
                this.numerDokZalKomField = value;
                this.RaisePropertyChanged("NumerDokZalKom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string NumerDokRef {
            get {
                return this.numerDokRefField;
            }
            set {
                this.numerDokRefField = value;
                this.RaisePropertyChanged("NumerDokRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string NumerDokBali {
            get {
                return this.numerDokBaliField;
            }
            set {
                this.numerDokBaliField = value;
                this.RaisePropertyChanged("NumerDokBali");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string DodDaneWyb {
            get {
                return this.dodDaneWybField;
            }
            set {
                this.dodDaneWybField = value;
                this.RaisePropertyChanged("DodDaneWyb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string InicjalySedziego {
            get {
                return this.inicjalySedziegoField;
            }
            set {
                this.inicjalySedziegoField = value;
                this.RaisePropertyChanged("InicjalySedziego");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentClarificationZDOBCreateOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:PaymentClarificationZDOBCreate", Order=0)]
        public Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateRequest PaymentClarificationZDOBCreateRequest;
        
        public PaymentClarificationZDOBCreateOutRequest() {
        }
        
        public PaymentClarificationZDOBCreateOutRequest(Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateRequest PaymentClarificationZDOBCreateRequest) {
            this.PaymentClarificationZDOBCreateRequest = PaymentClarificationZDOBCreateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentClarificationZDOBCreateOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:PaymentClarificationZDOBCreate", Order=0)]
        public Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateResponse PaymentClarificationZDOBCreateResponse;
        
        public PaymentClarificationZDOBCreateOutResponse() {
        }
        
        public PaymentClarificationZDOBCreateOutResponse(Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateResponse PaymentClarificationZDOBCreateResponse) {
            this.PaymentClarificationZDOBCreateResponse = PaymentClarificationZDOBCreateResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PaymentClarificationZDOBCreateOutChannel : Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOut, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentClarificationZDOBCreateOutClient : System.ServiceModel.ClientBase<Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOut>, Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOut {
        
        public PaymentClarificationZDOBCreateOutClient() {
        }
        
        public PaymentClarificationZDOBCreateOutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentClarificationZDOBCreateOutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentClarificationZDOBCreateOutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentClarificationZDOBCreateOutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOutResponse Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOut.PaymentClarificationZDOBCreateOut(Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOutRequest request) {
            return base.Channel.PaymentClarificationZDOBCreateOut(request);
        }
        
        public Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateResponse PaymentClarificationZDOBCreateOut(Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateRequest PaymentClarificationZDOBCreateRequest) {
            Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOutRequest inValue = new Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOutRequest();
            inValue.PaymentClarificationZDOBCreateRequest = PaymentClarificationZDOBCreateRequest;
            Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOutResponse retVal = ((Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOut)(this)).PaymentClarificationZDOBCreateOut(inValue);
            return retVal.PaymentClarificationZDOBCreateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOutResponse> Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOut.PaymentClarificationZDOBCreateOutAsync(Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOutRequest request) {
            return base.Channel.PaymentClarificationZDOBCreateOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOutResponse> PaymentClarificationZDOBCreateOutAsync(Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateRequest PaymentClarificationZDOBCreateRequest) {
            Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOutRequest inValue = new Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOutRequest();
            inValue.PaymentClarificationZDOBCreateRequest = PaymentClarificationZDOBCreateRequest;
            return ((Ex2PscdInterface.Ex2PscdPaymentClarificationZDOBCreateOutService.PaymentClarificationZDOBCreateOut)(this)).PaymentClarificationZDOBCreateOutAsync(inValue);
        }
    }
}
