//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:PaymentReservationCreate", ConfigurationName="Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOut")]
    public interface PaymentReservationCreateOut {
        
        // CODEGEN: Generating message contract since the operation PaymentReservationCreateOut is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOutResponse PaymentReservationCreateOut(Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOutResponse> PaymentReservationCreateOutAsync(Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class PaymentReservationCreateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Admin adminField;
        
        private PozycjaDoRezerwacji pozycjaDoRezerwacjiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Admin Admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
                this.RaisePropertyChanged("Admin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public PozycjaDoRezerwacji PozycjaDoRezerwacji {
            get {
                return this.pozycjaDoRezerwacjiField;
            }
            set {
                this.pozycjaDoRezerwacjiField = value;
                this.RaisePropertyChanged("PozycjaDoRezerwacji");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Admin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jednostkaGospodarczaField;
        
        private string iDKomunikatuField;
        
        private string iDSystemMerytorycznegoField;
        
        private string utworzonyDataField;
        
        private string utworzonyGodzField;
        
        private string uzytkownikField;
        
        private string hasloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string JednostkaGospodarcza {
            get {
                return this.jednostkaGospodarczaField;
            }
            set {
                this.jednostkaGospodarczaField = value;
                this.RaisePropertyChanged("JednostkaGospodarcza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IDSystemMerytorycznego {
            get {
                return this.iDSystemMerytorycznegoField;
            }
            set {
                this.iDSystemMerytorycznegoField = value;
                this.RaisePropertyChanged("IDSystemMerytorycznego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UtworzonyData {
            get {
                return this.utworzonyDataField;
            }
            set {
                this.utworzonyDataField = value;
                this.RaisePropertyChanged("UtworzonyData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string UtworzonyGodz {
            get {
                return this.utworzonyGodzField;
            }
            set {
                this.utworzonyGodzField = value;
                this.RaisePropertyChanged("UtworzonyGodz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Uzytkownik {
            get {
                return this.uzytkownikField;
            }
            set {
                this.uzytkownikField = value;
                this.RaisePropertyChanged("Uzytkownik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Haslo {
            get {
                return this.hasloField;
            }
            set {
                this.hasloField = value;
                this.RaisePropertyChanged("Haslo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Komunikat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDKomunikatuField;
        
        private string rodzajKomunikatuField;
        
        private string numerKomunikatuField;
        
        private string komunikat1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RodzajKomunikatu {
            get {
                return this.rodzajKomunikatuField;
            }
            set {
                this.rodzajKomunikatuField = value;
                this.RaisePropertyChanged("RodzajKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NumerKomunikatu {
            get {
                return this.numerKomunikatuField;
            }
            set {
                this.numerKomunikatuField = value;
                this.RaisePropertyChanged("NumerKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Komunikat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Komunikat1 {
            get {
                return this.komunikat1Field;
            }
            set {
                this.komunikat1Field = value;
                this.RaisePropertyChanged("Komunikat1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class PaymentReservationCreateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Komunikat[] komunikatyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Komunikat[] Komunikaty {
            get {
                return this.komunikatyField;
            }
            set {
                this.komunikatyField = value;
                this.RaisePropertyChanged("Komunikaty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class RezerwacjaPlatnosci : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sadField;
        
        private string sadFunkcjonalnyField;
        
        private string wydzialField;
        
        private string kwotaField;
        
        private string statusRezerwacjaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Sad {
            get {
                return this.sadField;
            }
            set {
                this.sadField = value;
                this.RaisePropertyChanged("Sad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SadFunkcjonalny {
            get {
                return this.sadFunkcjonalnyField;
            }
            set {
                this.sadFunkcjonalnyField = value;
                this.RaisePropertyChanged("SadFunkcjonalny");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Wydzial {
            get {
                return this.wydzialField;
            }
            set {
                this.wydzialField = value;
                this.RaisePropertyChanged("Wydzial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Kwota {
            get {
                return this.kwotaField;
            }
            set {
                this.kwotaField = value;
                this.RaisePropertyChanged("Kwota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string StatusRezerwacja {
            get {
                return this.statusRezerwacjaField;
            }
            set {
                this.statusRezerwacjaField = value;
                this.RaisePropertyChanged("StatusRezerwacja");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class PozycjaPlatnosci : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string partiaPlatnosciIDField;
        
        private string partiaPlatnosciNrPozycjaField;
        
        private string jednostkaGospodarczaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PartiaPlatnosciID {
            get {
                return this.partiaPlatnosciIDField;
            }
            set {
                this.partiaPlatnosciIDField = value;
                this.RaisePropertyChanged("PartiaPlatnosciID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PartiaPlatnosciNrPozycja {
            get {
                return this.partiaPlatnosciNrPozycjaField;
            }
            set {
                this.partiaPlatnosciNrPozycjaField = value;
                this.RaisePropertyChanged("PartiaPlatnosciNrPozycja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string JednostkaGospodarcza {
            get {
                return this.jednostkaGospodarczaField;
            }
            set {
                this.jednostkaGospodarczaField = value;
                this.RaisePropertyChanged("JednostkaGospodarcza");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class PozycjaDoRezerwacji : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PozycjaPlatnosci pozycjaPlatnosciField;
        
        private RezerwacjaPlatnosci rezerwacjaPlatnosciField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PozycjaPlatnosci PozycjaPlatnosci {
            get {
                return this.pozycjaPlatnosciField;
            }
            set {
                this.pozycjaPlatnosciField = value;
                this.RaisePropertyChanged("PozycjaPlatnosci");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public RezerwacjaPlatnosci RezerwacjaPlatnosci {
            get {
                return this.rezerwacjaPlatnosciField;
            }
            set {
                this.rezerwacjaPlatnosciField = value;
                this.RaisePropertyChanged("RezerwacjaPlatnosci");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentReservationCreateOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:PaymentReservationCreate", Order=0)]
        public Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateRequest PaymentReservationCreateRequest;
        
        public PaymentReservationCreateOutRequest() {
        }
        
        public PaymentReservationCreateOutRequest(Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateRequest PaymentReservationCreateRequest) {
            this.PaymentReservationCreateRequest = PaymentReservationCreateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentReservationCreateOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:PaymentReservationCreate", Order=0)]
        public Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateResponse PaymentReservationCreateResponse;
        
        public PaymentReservationCreateOutResponse() {
        }
        
        public PaymentReservationCreateOutResponse(Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateResponse PaymentReservationCreateResponse) {
            this.PaymentReservationCreateResponse = PaymentReservationCreateResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PaymentReservationCreateOutChannel : Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOut, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentReservationCreateOutClient : System.ServiceModel.ClientBase<Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOut>, Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOut {
        
        public PaymentReservationCreateOutClient() {
        }
        
        public PaymentReservationCreateOutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentReservationCreateOutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentReservationCreateOutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentReservationCreateOutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOutResponse Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOut.PaymentReservationCreateOut(Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOutRequest request) {
            return base.Channel.PaymentReservationCreateOut(request);
        }
        
        public Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateResponse PaymentReservationCreateOut(Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateRequest PaymentReservationCreateRequest) {
            Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOutRequest inValue = new Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOutRequest();
            inValue.PaymentReservationCreateRequest = PaymentReservationCreateRequest;
            Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOutResponse retVal = ((Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOut)(this)).PaymentReservationCreateOut(inValue);
            return retVal.PaymentReservationCreateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOutResponse> Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOut.PaymentReservationCreateOutAsync(Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOutRequest request) {
            return base.Channel.PaymentReservationCreateOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOutResponse> PaymentReservationCreateOutAsync(Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateRequest PaymentReservationCreateRequest) {
            Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOutRequest inValue = new Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOutRequest();
            inValue.PaymentReservationCreateRequest = PaymentReservationCreateRequest;
            return ((Ex2PscdInterface.Ex2PscdPaymentReservationCreateOutService.PaymentReservationCreateOut)(this)).PaymentReservationCreateOutAsync(inValue);
        }
    }
}
