<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="DocumentBailiffListQueryOut" targetNamespace="urn:ms.gov.pl:EX2PSCD:DocumentBailiffListQuery"
    xmlns:p1="urn:ms.gov.pl:EX2PSCD:DocumentBailiffListQuery"
    xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
    xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:documentation/>
    <wsp:UsingPolicy wsdl:required="true"/>
    <wsp:Policy wsu:Id="OP_DocumentBailiffListQueryOut"/>
    <wsdl:types>
        <xsd:schema targetNamespace="urn:ms.gov.pl:EX2PSCD:Common"
            xmlns="urn:ms.gov.pl:EX2PSCD:Common"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:complexType name="DocumentBailiffListQueryResponse">
                <xsd:annotation>
                    <xsd:appinfo source="http://sap.com/xi/VersionID">5c7abb8b622a11eb8078000006d9f6a6</xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element name="RozrachunkiZKomornikiem" type="RozrachunkiZKomornikiem"/>
                    <xsd:element name="Komunikaty" type="Komunikaty"/>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="RozrachunkekZKomornikiem">
                <xsd:annotation>
                    <xsd:appinfo source="http://sap.com/xi/VersionID">774d26a25c8111eb8690000006d9f6a6</xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element name="NumerDokumentu">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">79db7ac85c8111eb8d54025041000001</xsd:appinfo>
                            <xsd:documentation>Numer dokumentu rozrachunków wg kont umów</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="12"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="DokumentWystornowany" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">79db7ac95c8111eb8fa7025041000001</xsd:appinfo>
                            <xsd:documentation>Numer dokumentu storna</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="12"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="RodzajDokumentu" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">79db95c05c8111eb858f025041000001</xsd:appinfo>
                            <xsd:documentation>Rodzaj dokumentu</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="2"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="DataDokumentu" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">79db95c15c8111ebb5ca025041000001</xsd:appinfo>
                            <xsd:documentation>Data dokumentu</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:pattern value="....-..-.."/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="DataKsiegowania" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">79db95c25c8111ebcf4a025041000001</xsd:appinfo>
                            <xsd:documentation>Data księgowania w dokumencie</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:pattern value="....-..-.."/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="NumerPartnera" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">79db95c35c8111eba0a7025041000001</xsd:appinfo>
                            <xsd:documentation>Numer partnera handlowego</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="10"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="Nazwisko" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">79db95c45c8111eb9082025041000001</xsd:appinfo>
                            <xsd:documentation>Nazwisko partnera handlowego (osoba)</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="40"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="Imie" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">79db95c55c8111ebcf3e025041000001</xsd:appinfo>
                            <xsd:documentation>Imię partnera handlowego (osoba)</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="40"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="Nazwa1" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">79db95c65c8111eb8e94025041000001</xsd:appinfo>
                            <xsd:documentation>Nazwa 1 organizacji</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="40"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="Nazwa2" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">79db95c75c8111ebb27d025041000001</xsd:appinfo>
                            <xsd:documentation>Nazwa 2 organizacji</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="40"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="NumerKontaUmowy" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">79db95c85c8111eb979e025041000001</xsd:appinfo>
                            <xsd:documentation>Numer konta umowy</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="12"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="PrzedmiotUmowy" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">79db95c95c8111eba75d025041000001</xsd:appinfo>
                            <xsd:documentation>Sygnatura sądowa</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="20"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="GlownaOperacja">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">79db95ca5c8111ebbf76025041000001</xsd:appinfo>
                            <xsd:documentation>Główna operacja poz. dokumentu</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="4"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="CzesciowaOperacja">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">79db95cb5c8111ebcad9025041000001</xsd:appinfo>
                            <xsd:documentation>Częśc. operacja poz. dokumentu</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="4"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="Kwota" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">79db95cc5c8111ebb66d025041000001</xsd:appinfo>
                            <xsd:documentation>Kwota w walucie krajowej ze znakiem +/-</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:decimal">
                                <xsd:totalDigits value="13"/>
                                <xsd:fractionDigits value="2"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="ZnacznikRozliczenia" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">79db95cd5c8111ebb9f3025041000001</xsd:appinfo>
                            <xsd:documentation>Status rozliczenia</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="1"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="Komunikaty">
                <xsd:annotation>
                    <xsd:appinfo source="http://sap.com/xi/VersionID">cbc364503b8811ebb319000006d9f6a6</xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element name="Komunikat" type="Komunikat" minOccurs="0" maxOccurs="unbounded"/>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="Admin">
                <xsd:annotation>
                    <xsd:documentation xml:lang="EN">Dane administracyjne dot. żądania</xsd:documentation>
                    <xsd:appinfo source="http://sap.com/xi/VersionID">256562f8622711eb82c8000006d9f6a6</xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element name="JednostkaGospodarcza">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">e866300d3b8511ebab5d025041000001</xsd:appinfo>
                            <xsd:documentation>Numer jednostki gospodarczej (4 cyfry)</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:pattern value="^\d{4}$"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="IDKomunikatu" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">e866300e3b8511ebae7d025041000001</xsd:appinfo>
                            <xsd:documentation>Identyfikacja komunikatu</xsd:documentation>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element name="IDSystemMerytorycznego" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">e866300f3b8511eba995025041000001</xsd:appinfo>
                            <xsd:documentation>Identyfikacja systemu merytorycznego</xsd:documentation>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element name="UtworzonyData">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">e86630103b8511ebbb15025041000001</xsd:appinfo>
                            <xsd:documentation>Data utworzenia komunikatu (format YYYYMMDD)</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:pattern value="^\d{8}$"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="UtworzonyGodz">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">e86630113b8511eba551025041000001</xsd:appinfo>
                            <xsd:documentation>Godzina utworzenia komunikatu (format HHMMSS)</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:pattern value="^\d{6}$"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="Uzytkownik">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">5fbdeefa571211ebbbed025041000001</xsd:appinfo>
                            <xsd:documentation>Nazwa użytkownika na systemie ZSRK ERP FI</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:pattern value="^\w{1"/>
                                <xsd:pattern value="12}$"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="Haslo">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">5fbdeefb571211eba86d025041000001</xsd:appinfo>
                            <xsd:documentation>Zaszyfrowane hasło użytkownika</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:pattern value="^[-A-Za-z0-9+\/]*={0"/>
                                <xsd:pattern value="3}$"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="Komunikat">
                <xsd:annotation>
                    <xsd:appinfo source="http://sap.com/xi/VersionID">1d18ad44622711ebabf6000006d9f6a6</xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element name="IDKomunikatu" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">a4c929653b8811ebb7d1025041000001</xsd:appinfo>
                            <xsd:documentation>Identyfikator żądania</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="20"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="RodzajKomunikatu" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">a4c929663b8811ebbe05025041000001</xsd:appinfo>
                            <xsd:documentation>Typ komunikatu</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="1"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="NumerKomunikatu" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">a4c929673b8811eba8c3025041000001</xsd:appinfo>
                            <xsd:documentation>Numer komunikatu</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:pattern value="^\d{3}$"/>
                                <xsd:maxLength value="3"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="Komunikat" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">a4c929683b8811ebbab2025041000001</xsd:appinfo>
                            <xsd:documentation>Tekstowa postać komunikatu</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="240"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="RozrachunkiZKomornikiem">
                <xsd:annotation>
                    <xsd:appinfo source="http://sap.com/xi/VersionID">8d2713b75c8011eb95b6000006d9f6a6</xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element name="RozrachunkekZKomornikiem" type="RozrachunkekZKomornikiem" minOccurs="0" maxOccurs="unbounded">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">a1deea045c8111eb858f025041000001</xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="DocumentBailiffListQueryRequest">
                <xsd:annotation>
                    <xsd:appinfo source="http://sap.com/xi/VersionID">58704160622a11eb854f000006d9f6a6</xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element name="Admin" type="Admin"/>
                    <xsd:element name="SygnaturaSadowa">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">6077680c5c8011eb808c025041000001</xsd:appinfo>
                            <xsd:documentation>Sygnatura sądowa</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="20"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="BezDokumentowWystornowanych" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">6077680d5c8011ebb80d025041000001</xsd:appinfo>
                            <xsd:documentation>Bez dokumentów wystornowanych</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="1"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="KomornikID" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">6077680e5c8011ebb137025041000001</xsd:appinfo>
                            <xsd:documentation>Numer partnera handlowego</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="10"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
        <xsd:schema targetNamespace="urn:ms.gov.pl:EX2PSCD:DocumentBailiffListQuery"
            xmlns:p6="urn:ms.gov.pl:EX2PSCD:Common"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns="urn:ms.gov.pl:EX2PSCD:DocumentBailiffListQuery">
            <xsd:import namespace="urn:ms.gov.pl:EX2PSCD:Common"/>
            <xsd:element name="DocumentBailiffListQueryRequest" type="p6:DocumentBailiffListQueryRequest"/>
            <xsd:element name="DocumentBailiffListQueryResponse" type="p6:DocumentBailiffListQueryResponse"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="DocumentBailiffListQueryRequest">
        <wsdl:documentation/>
        <wsdl:part name="DocumentBailiffListQueryRequest" element="p1:DocumentBailiffListQueryRequest"/>
    </wsdl:message>
    <wsdl:message name="DocumentBailiffListQueryResponse">
        <wsdl:documentation/>
        <wsdl:part name="DocumentBailiffListQueryResponse" element="p1:DocumentBailiffListQueryResponse"/>
    </wsdl:message>
    <wsdl:portType name="DocumentBailiffListQueryOut">
        <wsdl:documentation/>
        <wsdl:operation name="DocumentBailiffListQueryOut">
            <wsdl:documentation/>
            <wsp:Policy>
                <wsp:PolicyReference URI="#OP_DocumentBailiffListQueryOut"/>
            </wsp:Policy>
            <wsdl:input message="p1:DocumentBailiffListQueryRequest"/>
            <wsdl:output message="p1:DocumentBailiffListQueryResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="DocumentBailiffListQueryOutBinding" type="p1:DocumentBailiffListQueryOut">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"
            xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
        <wsdl:operation name="DocumentBailiffListQueryOut">
            <soap:operation soapAction="http://sap.com/xi/WebService/soap1.1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
            <wsdl:input>
                <soap:body use="literal"
                    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"
                    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="DocumentBailiffListQueryOutService">
        <wsdl:port name="HTTPS_Port" binding="p1:DocumentBailiffListQueryOutBinding">
            <soap:address location="https://sapwitl01.zsrk.ms.gov.pl:44300/XISOAPAdapter/MessageServlet?senderParty=&amp;senderService=EX2PSCDSender&amp;receiverParty=&amp;receiverService=&amp;interface=DocumentBailiffListQueryOut&amp;interfaceNamespace=urn%3Ams.gov.pl%3AEX2PSCD%3ADocumentBailiffListQuery"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>