<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="RelationCreateOut" targetNamespace="urn:ms.gov.pl:EX2PSCD:RelationCreate"
    xmlns:p1="urn:ms.gov.pl:EX2PSCD:RelationCreate"
    xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
    xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:documentation/>
    <wsp:UsingPolicy wsdl:required="true"/>
    <wsp:Policy wsu:Id="OP_RelationCreateOut"/>
    <wsdl:types>
        <xsd:schema targetNamespace="urn:ms.gov.pl:EX2PSCD:Common"
            xmlns="urn:ms.gov.pl:EX2PSCD:Common"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:complexType name="Relacja">
                <xsd:annotation>
                    <xsd:appinfo source="http://sap.com/xi/VersionID">16aec0975c8411ebc08e000006d9f6a6</xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element name="NumerKontaUmowy" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">193009cf5c8411ebcfea025041000001</xsd:appinfo>
                            <xsd:documentation>Numer konta umowy CHAR12</xsd:documentation>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element name="IDPrzedmiotuUmowy" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">193009d05c8411eb8b53025041000001</xsd:appinfo>
                            <xsd:documentation>Identyfikator przedmiotu umowy CHAR20</xsd:documentation>
                        </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="RelationCreateRequest">
                <xsd:annotation>
                    <xsd:appinfo source="http://sap.com/xi/VersionID">770a19555c8411ebba7f000006d9f6a6</xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element name="Admin" type="Admin">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">856ad9415c8411eb9419025041000001</xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element name="Relacja" type="Relacja">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">856ad9425c8411ebb187025041000001</xsd:appinfo>
                        </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="Komunikaty">
                <xsd:annotation>
                    <xsd:appinfo source="http://sap.com/xi/VersionID">cbc364503b8811ebb319000006d9f6a6</xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element name="Komunikat" type="Komunikat" minOccurs="0" maxOccurs="unbounded"/>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="Admin">
                <xsd:annotation>
                    <xsd:documentation xml:lang="EN">Dane administracyjne dot. żądania</xsd:documentation>
                    <xsd:appinfo source="http://sap.com/xi/VersionID">256562f8622711eb82c8000006d9f6a6</xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element name="JednostkaGospodarcza">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">e866300d3b8511ebab5d025041000001</xsd:appinfo>
                            <xsd:documentation>Numer jednostki gospodarczej (4 cyfry)</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:pattern value="^\d{4}$"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="IDKomunikatu" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">e866300e3b8511ebae7d025041000001</xsd:appinfo>
                            <xsd:documentation>Identyfikacja komunikatu</xsd:documentation>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element name="IDSystemMerytorycznego" type="xsd:string">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">e866300f3b8511eba995025041000001</xsd:appinfo>
                            <xsd:documentation>Identyfikacja systemu merytorycznego</xsd:documentation>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element name="UtworzonyData">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">e86630103b8511ebbb15025041000001</xsd:appinfo>
                            <xsd:documentation>Data utworzenia komunikatu (format YYYYMMDD)</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:pattern value="^\d{8}$"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="UtworzonyGodz">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">e86630113b8511eba551025041000001</xsd:appinfo>
                            <xsd:documentation>Godzina utworzenia komunikatu (format HHMMSS)</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:pattern value="^\d{6}$"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="Uzytkownik">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">5fbdeefa571211ebbbed025041000001</xsd:appinfo>
                            <xsd:documentation>Nazwa użytkownika na systemie ZSRK ERP FI</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:pattern value="^\w{1"/>
                                <xsd:pattern value="12}$"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="Haslo">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">5fbdeefb571211eba86d025041000001</xsd:appinfo>
                            <xsd:documentation>Zaszyfrowane hasło użytkownika</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:pattern value="^[-A-Za-z0-9+\/]*={0"/>
                                <xsd:pattern value="3}$"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="Komunikat">
                <xsd:annotation>
                    <xsd:appinfo source="http://sap.com/xi/VersionID">1d18ad44622711ebabf6000006d9f6a6</xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element name="IDKomunikatu" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">a4c929653b8811ebb7d1025041000001</xsd:appinfo>
                            <xsd:documentation>Identyfikator żądania</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="20"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="RodzajKomunikatu" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">a4c929663b8811ebbe05025041000001</xsd:appinfo>
                            <xsd:documentation>Typ komunikatu</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="1"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="NumerKomunikatu" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">a4c929673b8811eba8c3025041000001</xsd:appinfo>
                            <xsd:documentation>Numer komunikatu</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:pattern value="^\d{3}$"/>
                                <xsd:maxLength value="3"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="Komunikat" minOccurs="0">
                        <xsd:annotation>
                            <xsd:appinfo source="http://sap.com/xi/TextID">a4c929683b8811ebbab2025041000001</xsd:appinfo>
                            <xsd:documentation>Tekstowa postać komunikatu</xsd:documentation>
                        </xsd:annotation>
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="240"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="RelationCreateResponse">
                <xsd:annotation>
                    <xsd:appinfo source="http://sap.com/xi/VersionID">98caa9515c8411eb93fe000006d9f6a6</xsd:appinfo>
                </xsd:annotation>
                <xsd:sequence>
                    <xsd:element name="Komunikaty" type="Komunikaty"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
        <xsd:schema targetNamespace="urn:ms.gov.pl:EX2PSCD:RelationCreate"
            xmlns:p1="urn:ms.gov.pl:EX2PSCD:Common"
            xmlns="urn:ms.gov.pl:EX2PSCD:RelationCreate"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="urn:ms.gov.pl:EX2PSCD:Common"/>
            <xsd:element name="RelationCreateResponse" type="p1:RelationCreateResponse"/>
            <xsd:element name="RelationCreateRequest" type="p1:RelationCreateRequest"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="RelationCreateRequest">
        <wsdl:documentation/>
        <wsdl:part name="RelationCreateRequest" element="p1:RelationCreateRequest"/>
    </wsdl:message>
    <wsdl:message name="RelationCreateResponse">
        <wsdl:documentation/>
        <wsdl:part name="RelationCreateResponse" element="p1:RelationCreateResponse"/>
    </wsdl:message>
    <wsdl:portType name="RelationCreateOut">
        <wsdl:documentation/>
        <wsdl:operation name="RelationCreateOut">
            <wsdl:documentation/>
            <wsp:Policy>
                <wsp:PolicyReference URI="#OP_RelationCreateOut"/>
            </wsp:Policy>
            <wsdl:input message="p1:RelationCreateRequest"/>
            <wsdl:output message="p1:RelationCreateResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="RelationCreateOutBinding" type="p1:RelationCreateOut">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"
            xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
        <wsdl:operation name="RelationCreateOut">
            <soap:operation soapAction="http://sap.com/xi/WebService/soap1.1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
            <wsdl:input>
                <soap:body use="literal"
                    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"
                    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="RelationCreateOutService">
        <wsdl:port name="HTTPS_Port" binding="p1:RelationCreateOutBinding">
            <soap:address location="https://sapwitl01.zsrk.ms.gov.pl:44300/XISOAPAdapter/MessageServlet?senderParty=&amp;senderService=EX2PSCDSender&amp;receiverParty=&amp;receiverService=&amp;interface=RelationCreateOut&amp;interfaceNamespace=urn%3Ams.gov.pl%3AEX2PSCD%3ARelationCreate"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>