//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsInterfeces.Rup2ConsGetStatusContentSystemData {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ms.gov.pl:ISM:GetStatusContentSystemData", ConfigurationName="Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOut")]
    public interface GetStatusContentSystemDataOut {
        
        // CODEGEN: Generating message contract since the operation GetStatusContentSystemDataOut is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOutResponse GetStatusContentSystemDataOut(ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOutResponse> GetStatusContentSystemDataOutAsync(ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:ISM:Common")]
    public partial class GetStatusContentSystemDataRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Admin adminField;
        
        private string gUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Admin Admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
                this.RaisePropertyChanged("Admin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
                this.RaisePropertyChanged("GUID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:ISM:Common")]
    public partial class Admin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jednostkaGospodarczaField;
        
        private string iDKomunikatuField;
        
        private string iDSystemMerytorycznegoField;
        
        private string utworzonyDataField;
        
        private string utworzonyGodzField;
        
        private string uzytkownikField;
        
        private string hasloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string JednostkaGospodarcza {
            get {
                return this.jednostkaGospodarczaField;
            }
            set {
                this.jednostkaGospodarczaField = value;
                this.RaisePropertyChanged("JednostkaGospodarcza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IDSystemMerytorycznego {
            get {
                return this.iDSystemMerytorycznegoField;
            }
            set {
                this.iDSystemMerytorycznegoField = value;
                this.RaisePropertyChanged("IDSystemMerytorycznego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UtworzonyData {
            get {
                return this.utworzonyDataField;
            }
            set {
                this.utworzonyDataField = value;
                this.RaisePropertyChanged("UtworzonyData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string UtworzonyGodz {
            get {
                return this.utworzonyGodzField;
            }
            set {
                this.utworzonyGodzField = value;
                this.RaisePropertyChanged("UtworzonyGodz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Uzytkownik {
            get {
                return this.uzytkownikField;
            }
            set {
                this.uzytkownikField = value;
                this.RaisePropertyChanged("Uzytkownik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Haslo {
            get {
                return this.hasloField;
            }
            set {
                this.hasloField = value;
                this.RaisePropertyChanged("Haslo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:ISM:Common")]
    public partial class PozycjaKomunikat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tytulKomunikatuField;
        
        private string trescKomunikatuField;
        
        private string numerKlasyKomunikatuField;
        
        private string numerKomunikatuField;
        
        private string typKomunikatuField;
        
        private string parametr1Field;
        
        private string parametr2Field;
        
        private string parametr3Field;
        
        private string parametr4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TytulKomunikatu {
            get {
                return this.tytulKomunikatuField;
            }
            set {
                this.tytulKomunikatuField = value;
                this.RaisePropertyChanged("TytulKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TrescKomunikatu {
            get {
                return this.trescKomunikatuField;
            }
            set {
                this.trescKomunikatuField = value;
                this.RaisePropertyChanged("TrescKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NumerKlasyKomunikatu {
            get {
                return this.numerKlasyKomunikatuField;
            }
            set {
                this.numerKlasyKomunikatuField = value;
                this.RaisePropertyChanged("NumerKlasyKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NumerKomunikatu {
            get {
                return this.numerKomunikatuField;
            }
            set {
                this.numerKomunikatuField = value;
                this.RaisePropertyChanged("NumerKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TypKomunikatu {
            get {
                return this.typKomunikatuField;
            }
            set {
                this.typKomunikatuField = value;
                this.RaisePropertyChanged("TypKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Parametr1 {
            get {
                return this.parametr1Field;
            }
            set {
                this.parametr1Field = value;
                this.RaisePropertyChanged("Parametr1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Parametr2 {
            get {
                return this.parametr2Field;
            }
            set {
                this.parametr2Field = value;
                this.RaisePropertyChanged("Parametr2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Parametr3 {
            get {
                return this.parametr3Field;
            }
            set {
                this.parametr3Field = value;
                this.RaisePropertyChanged("Parametr3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Parametr4 {
            get {
                return this.parametr4Field;
            }
            set {
                this.parametr4Field = value;
                this.RaisePropertyChanged("Parametr4");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:ISM:Common")]
    public partial class GetStatusContentSystemDataResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PozycjaKomunikat[] listaKomunikatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PozycjaKomunikat[] ListaKomunikat {
            get {
                return this.listaKomunikatField;
            }
            set {
                this.listaKomunikatField = value;
                this.RaisePropertyChanged("ListaKomunikat");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusContentSystemDataOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:ISM:GetStatusContentSystemData", Order=0)]
        public ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataRequest GetStatusContentSystemDataRequest;
        
        public GetStatusContentSystemDataOutRequest() {
        }
        
        public GetStatusContentSystemDataOutRequest(ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataRequest GetStatusContentSystemDataRequest) {
            this.GetStatusContentSystemDataRequest = GetStatusContentSystemDataRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusContentSystemDataOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:ISM:GetStatusContentSystemData", Order=0)]
        public ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataResponse GetStatusContentSystemDataResponse;
        
        public GetStatusContentSystemDataOutResponse() {
        }
        
        public GetStatusContentSystemDataOutResponse(ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataResponse GetStatusContentSystemDataResponse) {
            this.GetStatusContentSystemDataResponse = GetStatusContentSystemDataResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetStatusContentSystemDataOutChannel : ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOut, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStatusContentSystemDataOutClient : System.ServiceModel.ClientBase<ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOut>, ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOut {
        
        public GetStatusContentSystemDataOutClient() {
        }
        
        public GetStatusContentSystemDataOutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetStatusContentSystemDataOutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetStatusContentSystemDataOutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetStatusContentSystemDataOutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOutResponse ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOut.GetStatusContentSystemDataOut(ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOutRequest request) {
            return base.Channel.GetStatusContentSystemDataOut(request);
        }
        
        public ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataResponse GetStatusContentSystemDataOut(ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataRequest GetStatusContentSystemDataRequest) {
            ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOutRequest inValue = new ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOutRequest();
            inValue.GetStatusContentSystemDataRequest = GetStatusContentSystemDataRequest;
            ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOutResponse retVal = ((ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOut)(this)).GetStatusContentSystemDataOut(inValue);
            return retVal.GetStatusContentSystemDataResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOutResponse> ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOut.GetStatusContentSystemDataOutAsync(ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOutRequest request) {
            return base.Channel.GetStatusContentSystemDataOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOutResponse> GetStatusContentSystemDataOutAsync(ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataRequest GetStatusContentSystemDataRequest) {
            ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOutRequest inValue = new ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOutRequest();
            inValue.GetStatusContentSystemDataRequest = GetStatusContentSystemDataRequest;
            return ((ConsInterfeces.Rup2ConsGetStatusContentSystemData.GetStatusContentSystemDataOut)(this)).GetStatusContentSystemDataOutAsync(inValue);
        }
    }
}
