//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:DocumentReferenceUpdate", ConfigurationName="Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOut")]
    public interface DocumentReferenceUpdateOut {
        
        // CODEGEN: Generating message contract since the operation DocumentReferenceUpdateOut is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOutResponse DocumentReferenceUpdateOut(Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOutResponse> DocumentReferenceUpdateOutAsync(Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class DocumentReferenceUpdateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Admin adminField;
        
        private PokazDokumentZrodlowy pokazDokumentZrodlowyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Admin Admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
                this.RaisePropertyChanged("Admin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public PokazDokumentZrodlowy PokazDokumentZrodlowy {
            get {
                return this.pokazDokumentZrodlowyField;
            }
            set {
                this.pokazDokumentZrodlowyField = value;
                this.RaisePropertyChanged("PokazDokumentZrodlowy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Admin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jednostkaGospodarczaField;
        
        private string iDKomunikatuField;
        
        private string iDSystemMerytorycznegoField;
        
        private string utworzonyDataField;
        
        private string utworzonyGodzField;
        
        private string uzytkownikField;
        
        private string hasloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string JednostkaGospodarcza {
            get {
                return this.jednostkaGospodarczaField;
            }
            set {
                this.jednostkaGospodarczaField = value;
                this.RaisePropertyChanged("JednostkaGospodarcza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IDSystemMerytorycznego {
            get {
                return this.iDSystemMerytorycznegoField;
            }
            set {
                this.iDSystemMerytorycznegoField = value;
                this.RaisePropertyChanged("IDSystemMerytorycznego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UtworzonyData {
            get {
                return this.utworzonyDataField;
            }
            set {
                this.utworzonyDataField = value;
                this.RaisePropertyChanged("UtworzonyData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string UtworzonyGodz {
            get {
                return this.utworzonyGodzField;
            }
            set {
                this.utworzonyGodzField = value;
                this.RaisePropertyChanged("UtworzonyGodz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Uzytkownik {
            get {
                return this.uzytkownikField;
            }
            set {
                this.uzytkownikField = value;
                this.RaisePropertyChanged("Uzytkownik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Haslo {
            get {
                return this.hasloField;
            }
            set {
                this.hasloField = value;
                this.RaisePropertyChanged("Haslo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Komunikat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDKomunikatuField;
        
        private string rodzajKomunikatuField;
        
        private string numerKomunikatuField;
        
        private string komunikat1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RodzajKomunikatu {
            get {
                return this.rodzajKomunikatuField;
            }
            set {
                this.rodzajKomunikatuField = value;
                this.RaisePropertyChanged("RodzajKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NumerKomunikatu {
            get {
                return this.numerKomunikatuField;
            }
            set {
                this.numerKomunikatuField = value;
                this.RaisePropertyChanged("NumerKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Komunikat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Komunikat1 {
            get {
                return this.komunikat1Field;
            }
            set {
                this.komunikat1Field = value;
                this.RaisePropertyChanged("Komunikat1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class DocumentReferenceUpdateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Komunikat[] komunikatyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Komunikat[] Komunikaty {
            get {
                return this.komunikatyField;
            }
            set {
                this.komunikatyField = value;
                this.RaisePropertyChanged("Komunikaty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class PokazDokumentZrodlowy : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numerDokumentuStornowanegoField;
        
        private string numerDokumentuZrodlowegoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NumerDokumentuStornowanego {
            get {
                return this.numerDokumentuStornowanegoField;
            }
            set {
                this.numerDokumentuStornowanegoField = value;
                this.RaisePropertyChanged("NumerDokumentuStornowanego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NumerDokumentuZrodlowego {
            get {
                return this.numerDokumentuZrodlowegoField;
            }
            set {
                this.numerDokumentuZrodlowegoField = value;
                this.RaisePropertyChanged("NumerDokumentuZrodlowego");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocumentReferenceUpdateOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:DocumentReferenceUpdate", Order=0)]
        public Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateRequest DocumentReferenceUpdateRequest;
        
        public DocumentReferenceUpdateOutRequest() {
        }
        
        public DocumentReferenceUpdateOutRequest(Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateRequest DocumentReferenceUpdateRequest) {
            this.DocumentReferenceUpdateRequest = DocumentReferenceUpdateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocumentReferenceUpdateOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:DocumentReferenceUpdate", Order=0)]
        public Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateResponse DocumentReferenceUpdateResponse;
        
        public DocumentReferenceUpdateOutResponse() {
        }
        
        public DocumentReferenceUpdateOutResponse(Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateResponse DocumentReferenceUpdateResponse) {
            this.DocumentReferenceUpdateResponse = DocumentReferenceUpdateResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocumentReferenceUpdateOutChannel : Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOut, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentReferenceUpdateOutClient : System.ServiceModel.ClientBase<Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOut>, Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOut {
        
        public DocumentReferenceUpdateOutClient() {
        }
        
        public DocumentReferenceUpdateOutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentReferenceUpdateOutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentReferenceUpdateOutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentReferenceUpdateOutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOutResponse Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOut.DocumentReferenceUpdateOut(Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOutRequest request) {
            return base.Channel.DocumentReferenceUpdateOut(request);
        }
        
        public Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateResponse DocumentReferenceUpdateOut(Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateRequest DocumentReferenceUpdateRequest) {
            Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOutRequest inValue = new Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOutRequest();
            inValue.DocumentReferenceUpdateRequest = DocumentReferenceUpdateRequest;
            Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOutResponse retVal = ((Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOut)(this)).DocumentReferenceUpdateOut(inValue);
            return retVal.DocumentReferenceUpdateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOutResponse> Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOut.DocumentReferenceUpdateOutAsync(Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOutRequest request) {
            return base.Channel.DocumentReferenceUpdateOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOutResponse> DocumentReferenceUpdateOutAsync(Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateRequest DocumentReferenceUpdateRequest) {
            Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOutRequest inValue = new Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOutRequest();
            inValue.DocumentReferenceUpdateRequest = DocumentReferenceUpdateRequest;
            return ((Ex2PscdInterface.Ex2PscdDocumentReferenceUpdateOutService.DocumentReferenceUpdateOut)(this)).DocumentReferenceUpdateOutAsync(inValue);
        }
    }
}
