//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:DocumentDebtStateUpdate", ConfigurationName="Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOut")]
    public interface DocumentDebtStateUpdateOut {
        
        // CODEGEN: Generating message contract since the operation DocumentDebtStateUpdateOut is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOutResponse DocumentDebtStateUpdateOut(Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOutResponse> DocumentDebtStateUpdateOutAsync(Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class DocumentDebtStateUpdateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Admin adminField;
        
        private ZmianaStatusuNaleznosci zmianaStatusuNaleznosciField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Admin Admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
                this.RaisePropertyChanged("Admin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ZmianaStatusuNaleznosci ZmianaStatusuNaleznosci {
            get {
                return this.zmianaStatusuNaleznosciField;
            }
            set {
                this.zmianaStatusuNaleznosciField = value;
                this.RaisePropertyChanged("ZmianaStatusuNaleznosci");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Admin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jednostkaGospodarczaField;
        
        private string iDKomunikatuField;
        
        private string iDSystemMerytorycznegoField;
        
        private string utworzonyDataField;
        
        private string utworzonyGodzField;
        
        private string uzytkownikField;
        
        private string hasloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string JednostkaGospodarcza {
            get {
                return this.jednostkaGospodarczaField;
            }
            set {
                this.jednostkaGospodarczaField = value;
                this.RaisePropertyChanged("JednostkaGospodarcza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IDSystemMerytorycznego {
            get {
                return this.iDSystemMerytorycznegoField;
            }
            set {
                this.iDSystemMerytorycznegoField = value;
                this.RaisePropertyChanged("IDSystemMerytorycznego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UtworzonyData {
            get {
                return this.utworzonyDataField;
            }
            set {
                this.utworzonyDataField = value;
                this.RaisePropertyChanged("UtworzonyData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string UtworzonyGodz {
            get {
                return this.utworzonyGodzField;
            }
            set {
                this.utworzonyGodzField = value;
                this.RaisePropertyChanged("UtworzonyGodz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Uzytkownik {
            get {
                return this.uzytkownikField;
            }
            set {
                this.uzytkownikField = value;
                this.RaisePropertyChanged("Uzytkownik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Haslo {
            get {
                return this.hasloField;
            }
            set {
                this.hasloField = value;
                this.RaisePropertyChanged("Haslo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Komunikat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDKomunikatuField;
        
        private string rodzajKomunikatuField;
        
        private string numerKomunikatuField;
        
        private string komunikat1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RodzajKomunikatu {
            get {
                return this.rodzajKomunikatuField;
            }
            set {
                this.rodzajKomunikatuField = value;
                this.RaisePropertyChanged("RodzajKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NumerKomunikatu {
            get {
                return this.numerKomunikatuField;
            }
            set {
                this.numerKomunikatuField = value;
                this.RaisePropertyChanged("NumerKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Komunikat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Komunikat1 {
            get {
                return this.komunikat1Field;
            }
            set {
                this.komunikat1Field = value;
                this.RaisePropertyChanged("Komunikat1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class DocumentDebtStateUpdateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Komunikat[] komunikatyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Komunikat[] Komunikaty {
            get {
                return this.komunikatyField;
            }
            set {
                this.komunikatyField = value;
                this.RaisePropertyChanged("Komunikaty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class ZmianaStatusuNaleznosci : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numerDokumentuRozrachunkowField;
        
        private string stanNaleznosciField;
        
        private string poczatekStanuNaleznosciField;
        
        private string uzytkownikField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NumerDokumentuRozrachunkow {
            get {
                return this.numerDokumentuRozrachunkowField;
            }
            set {
                this.numerDokumentuRozrachunkowField = value;
                this.RaisePropertyChanged("NumerDokumentuRozrachunkow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string StanNaleznosci {
            get {
                return this.stanNaleznosciField;
            }
            set {
                this.stanNaleznosciField = value;
                this.RaisePropertyChanged("StanNaleznosci");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PoczatekStanuNaleznosci {
            get {
                return this.poczatekStanuNaleznosciField;
            }
            set {
                this.poczatekStanuNaleznosciField = value;
                this.RaisePropertyChanged("PoczatekStanuNaleznosci");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Uzytkownik {
            get {
                return this.uzytkownikField;
            }
            set {
                this.uzytkownikField = value;
                this.RaisePropertyChanged("Uzytkownik");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocumentDebtStateUpdateOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:DocumentDebtStateUpdate", Order=0)]
        public Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateRequest DocumentDebtStateUpdateRequest;
        
        public DocumentDebtStateUpdateOutRequest() {
        }
        
        public DocumentDebtStateUpdateOutRequest(Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateRequest DocumentDebtStateUpdateRequest) {
            this.DocumentDebtStateUpdateRequest = DocumentDebtStateUpdateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocumentDebtStateUpdateOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:DocumentDebtStateUpdate", Order=0)]
        public Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateResponse DocumentDebtStateUpdateResponse;
        
        public DocumentDebtStateUpdateOutResponse() {
        }
        
        public DocumentDebtStateUpdateOutResponse(Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateResponse DocumentDebtStateUpdateResponse) {
            this.DocumentDebtStateUpdateResponse = DocumentDebtStateUpdateResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocumentDebtStateUpdateOutChannel : Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOut, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentDebtStateUpdateOutClient : System.ServiceModel.ClientBase<Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOut>, Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOut {
        
        public DocumentDebtStateUpdateOutClient() {
        }
        
        public DocumentDebtStateUpdateOutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentDebtStateUpdateOutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentDebtStateUpdateOutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentDebtStateUpdateOutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOutResponse Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOut.DocumentDebtStateUpdateOut(Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOutRequest request) {
            return base.Channel.DocumentDebtStateUpdateOut(request);
        }
        
        public Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateResponse DocumentDebtStateUpdateOut(Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateRequest DocumentDebtStateUpdateRequest) {
            Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOutRequest inValue = new Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOutRequest();
            inValue.DocumentDebtStateUpdateRequest = DocumentDebtStateUpdateRequest;
            Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOutResponse retVal = ((Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOut)(this)).DocumentDebtStateUpdateOut(inValue);
            return retVal.DocumentDebtStateUpdateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOutResponse> Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOut.DocumentDebtStateUpdateOutAsync(Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOutRequest request) {
            return base.Channel.DocumentDebtStateUpdateOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOutResponse> DocumentDebtStateUpdateOutAsync(Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateRequest DocumentDebtStateUpdateRequest) {
            Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOutRequest inValue = new Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOutRequest();
            inValue.DocumentDebtStateUpdateRequest = DocumentDebtStateUpdateRequest;
            return ((Ex2PscdInterface.Ex2PscdDocumentDebtStateUpdateOutService.DocumentDebtStateUpdateOut)(this)).DocumentDebtStateUpdateOutAsync(inValue);
        }
    }
}
