//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:DebtorDepositListQuery", ConfigurationName="Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOut")]
    public interface DebtorDepositListQueryOut {
        
        // CODEGEN: Generating message contract since the operation DebtorDepositListQueryOut is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOutResponse DebtorDepositListQueryOut(Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOutResponse> DebtorDepositListQueryOutAsync(Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class DebtorDepositListQueryRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Admin adminField;
        
        private string numerPartneraField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Admin Admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
                this.RaisePropertyChanged("Admin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NumerPartnera {
            get {
                return this.numerPartneraField;
            }
            set {
                this.numerPartneraField = value;
                this.RaisePropertyChanged("NumerPartnera");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Admin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jednostkaGospodarczaField;
        
        private string iDKomunikatuField;
        
        private string iDSystemMerytorycznegoField;
        
        private string utworzonyDataField;
        
        private string utworzonyGodzField;
        
        private string uzytkownikField;
        
        private string hasloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string JednostkaGospodarcza {
            get {
                return this.jednostkaGospodarczaField;
            }
            set {
                this.jednostkaGospodarczaField = value;
                this.RaisePropertyChanged("JednostkaGospodarcza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IDSystemMerytorycznego {
            get {
                return this.iDSystemMerytorycznegoField;
            }
            set {
                this.iDSystemMerytorycznegoField = value;
                this.RaisePropertyChanged("IDSystemMerytorycznego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UtworzonyData {
            get {
                return this.utworzonyDataField;
            }
            set {
                this.utworzonyDataField = value;
                this.RaisePropertyChanged("UtworzonyData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string UtworzonyGodz {
            get {
                return this.utworzonyGodzField;
            }
            set {
                this.utworzonyGodzField = value;
                this.RaisePropertyChanged("UtworzonyGodz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Uzytkownik {
            get {
                return this.uzytkownikField;
            }
            set {
                this.uzytkownikField = value;
                this.RaisePropertyChanged("Uzytkownik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Haslo {
            get {
                return this.hasloField;
            }
            set {
                this.hasloField = value;
                this.RaisePropertyChanged("Haslo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Komunikat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDKomunikatuField;
        
        private string rodzajKomunikatuField;
        
        private string numerKomunikatuField;
        
        private string komunikat1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RodzajKomunikatu {
            get {
                return this.rodzajKomunikatuField;
            }
            set {
                this.rodzajKomunikatuField = value;
                this.RaisePropertyChanged("RodzajKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NumerKomunikatu {
            get {
                return this.numerKomunikatuField;
            }
            set {
                this.numerKomunikatuField = value;
                this.RaisePropertyChanged("NumerKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Komunikat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Komunikat1 {
            get {
                return this.komunikat1Field;
            }
            set {
                this.komunikat1Field = value;
                this.RaisePropertyChanged("Komunikat1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class DepozytDluznika : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numerPartneraField;
        
        private string numerKontaUmowyField;
        
        private string sygnaturaSadowaField;
        
        private string oznaczeniePrzedmiotuUmowyField;
        
        private decimal kwotaField;
        
        private bool kwotaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NumerPartnera {
            get {
                return this.numerPartneraField;
            }
            set {
                this.numerPartneraField = value;
                this.RaisePropertyChanged("NumerPartnera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NumerKontaUmowy {
            get {
                return this.numerKontaUmowyField;
            }
            set {
                this.numerKontaUmowyField = value;
                this.RaisePropertyChanged("NumerKontaUmowy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SygnaturaSadowa {
            get {
                return this.sygnaturaSadowaField;
            }
            set {
                this.sygnaturaSadowaField = value;
                this.RaisePropertyChanged("SygnaturaSadowa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string OznaczeniePrzedmiotuUmowy {
            get {
                return this.oznaczeniePrzedmiotuUmowyField;
            }
            set {
                this.oznaczeniePrzedmiotuUmowyField = value;
                this.RaisePropertyChanged("OznaczeniePrzedmiotuUmowy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal Kwota {
            get {
                return this.kwotaField;
            }
            set {
                this.kwotaField = value;
                this.RaisePropertyChanged("Kwota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KwotaSpecified {
            get {
                return this.kwotaFieldSpecified;
            }
            set {
                this.kwotaFieldSpecified = value;
                this.RaisePropertyChanged("KwotaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class DebtorDepositListQueryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DepozytDluznika[] depozytyDluznikaField;
        
        private Komunikat[] komunikatyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DepozytDluznika[] DepozytyDluznika {
            get {
                return this.depozytyDluznikaField;
            }
            set {
                this.depozytyDluznikaField = value;
                this.RaisePropertyChanged("DepozytyDluznika");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Komunikat[] Komunikaty {
            get {
                return this.komunikatyField;
            }
            set {
                this.komunikatyField = value;
                this.RaisePropertyChanged("Komunikaty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DebtorDepositListQueryOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:DebtorDepositListQuery", Order=0)]
        public Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryRequest DebtorDepositListQueryRequest;
        
        public DebtorDepositListQueryOutRequest() {
        }
        
        public DebtorDepositListQueryOutRequest(Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryRequest DebtorDepositListQueryRequest) {
            this.DebtorDepositListQueryRequest = DebtorDepositListQueryRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DebtorDepositListQueryOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:DebtorDepositListQuery", Order=0)]
        public Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryResponse DebtorDepositListQueryResponse;
        
        public DebtorDepositListQueryOutResponse() {
        }
        
        public DebtorDepositListQueryOutResponse(Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryResponse DebtorDepositListQueryResponse) {
            this.DebtorDepositListQueryResponse = DebtorDepositListQueryResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DebtorDepositListQueryOutChannel : Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOut, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DebtorDepositListQueryOutClient : System.ServiceModel.ClientBase<Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOut>, Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOut {
        
        public DebtorDepositListQueryOutClient() {
        }
        
        public DebtorDepositListQueryOutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DebtorDepositListQueryOutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DebtorDepositListQueryOutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DebtorDepositListQueryOutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOutResponse Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOut.DebtorDepositListQueryOut(Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOutRequest request) {
            return base.Channel.DebtorDepositListQueryOut(request);
        }
        
        public Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryResponse DebtorDepositListQueryOut(Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryRequest DebtorDepositListQueryRequest) {
            Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOutRequest inValue = new Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOutRequest();
            inValue.DebtorDepositListQueryRequest = DebtorDepositListQueryRequest;
            Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOutResponse retVal = ((Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOut)(this)).DebtorDepositListQueryOut(inValue);
            return retVal.DebtorDepositListQueryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOutResponse> Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOut.DebtorDepositListQueryOutAsync(Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOutRequest request) {
            return base.Channel.DebtorDepositListQueryOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOutResponse> DebtorDepositListQueryOutAsync(Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryRequest DebtorDepositListQueryRequest) {
            Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOutRequest inValue = new Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOutRequest();
            inValue.DebtorDepositListQueryRequest = DebtorDepositListQueryRequest;
            return ((Ex2PscdInterface.Ex2PscdDebtorDepositListQueryOutService.DebtorDepositListQueryOut)(this)).DebtorDepositListQueryOutAsync(inValue);
        }
    }
}
