//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RupBig.ServiceReferenceBigMain {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ms.gov.pl/ig2big/common", ConfigurationName="ServiceReferenceBigMain.IG2BIG_packageSubmitRequest_out")]
    public interface IG2BIG_packageSubmitRequest_out {
        
        // CODEGEN: Generating message contract since the operation IG2BIG_packageSubmitRequest_out is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RupBig.ServiceReferenceBigMain.IG2BIG_packageSubmitRequest_outResponse IG2BIG_packageSubmitRequest_out(RupBig.ServiceReferenceBigMain.IG2BIG_packageSubmitRequest_outRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public partial class Package : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Credentials[] credentialsField;
        
        private PackageSubmit packageSubmitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("credentials", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Credentials[] credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
                this.RaisePropertyChanged("credentials");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public PackageSubmit packageSubmit {
            get {
                return this.packageSubmitField;
            }
            set {
                this.packageSubmitField = value;
                this.RaisePropertyChanged("packageSubmit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public partial class Credentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CredentialsBig_id big_idField;
        
        private string subscriberIdField;
        
        private string userIdField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CredentialsBig_id big_id {
            get {
                return this.big_idField;
            }
            set {
                this.big_idField = value;
                this.RaisePropertyChanged("big_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string subscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("subscriberId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.ig2big.org/ws/v1/types")]
    public enum CredentialsBig_id {
        
        /// <remarks/>
        IM,
        
        /// <remarks/>
        KBIG,
        
        /// <remarks/>
        ERIF,
        
        /// <remarks/>
        KRD,
        
        /// <remarks/>
        KIDT,
        
        /// <remarks/>
        BNP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public partial class Confirmation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime receptionDateTimeField;
        
        private string ackStatusField;
        
        private string ackMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime receptionDateTime {
            get {
                return this.receptionDateTimeField;
            }
            set {
                this.receptionDateTimeField = value;
                this.RaisePropertyChanged("receptionDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string AckStatus {
            get {
                return this.ackStatusField;
            }
            set {
                this.ackStatusField = value;
                this.RaisePropertyChanged("AckStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string AckMessage {
            get {
                return this.ackMessageField;
            }
            set {
                this.ackMessageField = value;
                this.RaisePropertyChanged("AckMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public partial class InformationSelector : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string debtorIdField;
        
        private string liabilityIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string debtorId {
            get {
                return this.debtorIdField;
            }
            set {
                this.debtorIdField = value;
                this.RaisePropertyChanged("debtorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string liabilityId {
            get {
                return this.liabilityIdField;
            }
            set {
                this.liabilityIdField = value;
                this.RaisePropertyChanged("liabilityId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public partial class BlockInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string debtorIdField;
        
        private string liabilityIdField;
        
        private System.DateTime shareSuspensionFinalDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string debtorId {
            get {
                return this.debtorIdField;
            }
            set {
                this.debtorIdField = value;
                this.RaisePropertyChanged("debtorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string liabilityId {
            get {
                return this.liabilityIdField;
            }
            set {
                this.liabilityIdField = value;
                this.RaisePropertyChanged("liabilityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime shareSuspensionFinalDate {
            get {
                return this.shareSuspensionFinalDateField;
            }
            set {
                this.shareSuspensionFinalDateField = value;
                this.RaisePropertyChanged("shareSuspensionFinalDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public partial class EnforceableTitle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string enforceableTitleIdField;
        
        private string adjudicatingBodyField;
        
        private System.DateTime issueDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string enforceableTitleId {
            get {
                return this.enforceableTitleIdField;
            }
            set {
                this.enforceableTitleIdField = value;
                this.RaisePropertyChanged("enforceableTitleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string adjudicatingBody {
            get {
                return this.adjudicatingBodyField;
            }
            set {
                this.adjudicatingBodyField = value;
                this.RaisePropertyChanged("adjudicatingBody");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime issueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
                this.RaisePropertyChanged("issueDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public partial class LegalTitle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EnforceableTitle enforceableTitleField;
        
        private string otherTitleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public EnforceableTitle enforceableTitle {
            get {
                return this.enforceableTitleField;
            }
            set {
                this.enforceableTitleField = value;
                this.RaisePropertyChanged("enforceableTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string otherTitle {
            get {
                return this.otherTitleField;
            }
            set {
                this.otherTitleField = value;
                this.RaisePropertyChanged("otherTitle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public partial class Liability : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string liabilityIdField;
        
        private bool institutionDataShareRestrictedField;
        
        private System.DateTime shareSuspensionFinalDateField;
        
        private bool shareSuspensionFinalDateFieldSpecified;
        
        private liabilityTypeEnum liabilityTypeField;
        
        private LegalTitle legalTitleField;
        
        private currencyEnum currencyField;
        
        private decimal liabilityAmountField;
        
        private bool liabilityAmountFieldSpecified;
        
        private decimal arrearsAmountField;
        
        private decimal disputedAmountField;
        
        private bool disputedAmountFieldSpecified;
        
        private System.DateTime arrearsRiseDateField;
        
        private System.DateTime paymentRequestDispatchDateField;
        
        private bool paymentRequestDispatchDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string liabilityId {
            get {
                return this.liabilityIdField;
            }
            set {
                this.liabilityIdField = value;
                this.RaisePropertyChanged("liabilityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool institutionDataShareRestricted {
            get {
                return this.institutionDataShareRestrictedField;
            }
            set {
                this.institutionDataShareRestrictedField = value;
                this.RaisePropertyChanged("institutionDataShareRestricted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime shareSuspensionFinalDate {
            get {
                return this.shareSuspensionFinalDateField;
            }
            set {
                this.shareSuspensionFinalDateField = value;
                this.RaisePropertyChanged("shareSuspensionFinalDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shareSuspensionFinalDateSpecified {
            get {
                return this.shareSuspensionFinalDateFieldSpecified;
            }
            set {
                this.shareSuspensionFinalDateFieldSpecified = value;
                this.RaisePropertyChanged("shareSuspensionFinalDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public liabilityTypeEnum liabilityType {
            get {
                return this.liabilityTypeField;
            }
            set {
                this.liabilityTypeField = value;
                this.RaisePropertyChanged("liabilityType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public LegalTitle legalTitle {
            get {
                return this.legalTitleField;
            }
            set {
                this.legalTitleField = value;
                this.RaisePropertyChanged("legalTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public currencyEnum currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal liabilityAmount {
            get {
                return this.liabilityAmountField;
            }
            set {
                this.liabilityAmountField = value;
                this.RaisePropertyChanged("liabilityAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool liabilityAmountSpecified {
            get {
                return this.liabilityAmountFieldSpecified;
            }
            set {
                this.liabilityAmountFieldSpecified = value;
                this.RaisePropertyChanged("liabilityAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal arrearsAmount {
            get {
                return this.arrearsAmountField;
            }
            set {
                this.arrearsAmountField = value;
                this.RaisePropertyChanged("arrearsAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal disputedAmount {
            get {
                return this.disputedAmountField;
            }
            set {
                this.disputedAmountField = value;
                this.RaisePropertyChanged("disputedAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool disputedAmountSpecified {
            get {
                return this.disputedAmountFieldSpecified;
            }
            set {
                this.disputedAmountFieldSpecified = value;
                this.RaisePropertyChanged("disputedAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=9)]
        public System.DateTime arrearsRiseDate {
            get {
                return this.arrearsRiseDateField;
            }
            set {
                this.arrearsRiseDateField = value;
                this.RaisePropertyChanged("arrearsRiseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=10)]
        public System.DateTime paymentRequestDispatchDate {
            get {
                return this.paymentRequestDispatchDateField;
            }
            set {
                this.paymentRequestDispatchDateField = value;
                this.RaisePropertyChanged("paymentRequestDispatchDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentRequestDispatchDateSpecified {
            get {
                return this.paymentRequestDispatchDateFieldSpecified;
            }
            set {
                this.paymentRequestDispatchDateFieldSpecified = value;
                this.RaisePropertyChanged("paymentRequestDispatchDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public enum liabilityTypeEnum {
        
        /// <remarks/>
        fine,
        
        /// <remarks/>
        compensation,
        
        /// <remarks/>
        forfeit,
        
        /// <remarks/>
        courtCosts,
        
        /// <remarks/>
        monetaryPenalty,
        
        /// <remarks/>
        compensatoryDamages,
        
        /// <remarks/>
        cashBenefits,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public enum currencyEnum {
        
        /// <remarks/>
        USD,
        
        /// <remarks/>
        AUD,
        
        /// <remarks/>
        CAD,
        
        /// <remarks/>
        EUR,
        
        /// <remarks/>
        HUF,
        
        /// <remarks/>
        CHF,
        
        /// <remarks/>
        GBP,
        
        /// <remarks/>
        JPY,
        
        /// <remarks/>
        CZK,
        
        /// <remarks/>
        DKK,
        
        /// <remarks/>
        EEK,
        
        /// <remarks/>
        NOK,
        
        /// <remarks/>
        SEK,
        
        /// <remarks/>
        RUB,
        
        /// <remarks/>
        PLN,
        
        /// <remarks/>
        GRD,
        
        /// <remarks/>
        PTE,
        
        /// <remarks/>
        BEF,
        
        /// <remarks/>
        FRF,
        
        /// <remarks/>
        LUF,
        
        /// <remarks/>
        IEP,
        
        /// <remarks/>
        NLG,
        
        /// <remarks/>
        ITL,
        
        /// <remarks/>
        FIM,
        
        /// <remarks/>
        DEM,
        
        /// <remarks/>
        ESP,
        
        /// <remarks/>
        ATS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private countryEnum countryField;
        
        private string postcodeField;
        
        private string cityField;
        
        private string streetField;
        
        private string houseNumberField;
        
        private string localNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public countryEnum country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
                this.RaisePropertyChanged("postcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string houseNumber {
            get {
                return this.houseNumberField;
            }
            set {
                this.houseNumberField = value;
                this.RaisePropertyChanged("houseNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string localNumber {
            get {
                return this.localNumberField;
            }
            set {
                this.localNumberField = value;
                this.RaisePropertyChanged("localNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public enum countryEnum {
        
        /// <remarks/>
        ABW,
        
        /// <remarks/>
        AFG,
        
        /// <remarks/>
        AGO,
        
        /// <remarks/>
        AIA,
        
        /// <remarks/>
        ALA,
        
        /// <remarks/>
        ALB,
        
        /// <remarks/>
        AND,
        
        /// <remarks/>
        ARE,
        
        /// <remarks/>
        ARG,
        
        /// <remarks/>
        ARM,
        
        /// <remarks/>
        ASM,
        
        /// <remarks/>
        ATA,
        
        /// <remarks/>
        ATF,
        
        /// <remarks/>
        ATG,
        
        /// <remarks/>
        AUS,
        
        /// <remarks/>
        AUT,
        
        /// <remarks/>
        AZE,
        
        /// <remarks/>
        BDI,
        
        /// <remarks/>
        BEL,
        
        /// <remarks/>
        BEN,
        
        /// <remarks/>
        BES,
        
        /// <remarks/>
        BFA,
        
        /// <remarks/>
        BGD,
        
        /// <remarks/>
        BGR,
        
        /// <remarks/>
        BHR,
        
        /// <remarks/>
        BHS,
        
        /// <remarks/>
        BIH,
        
        /// <remarks/>
        BLM,
        
        /// <remarks/>
        BLR,
        
        /// <remarks/>
        BLZ,
        
        /// <remarks/>
        BMU,
        
        /// <remarks/>
        BOL,
        
        /// <remarks/>
        BRA,
        
        /// <remarks/>
        BRB,
        
        /// <remarks/>
        BRN,
        
        /// <remarks/>
        BTN,
        
        /// <remarks/>
        BVT,
        
        /// <remarks/>
        BWA,
        
        /// <remarks/>
        CAF,
        
        /// <remarks/>
        CAN,
        
        /// <remarks/>
        CCK,
        
        /// <remarks/>
        CHE,
        
        /// <remarks/>
        CHL,
        
        /// <remarks/>
        CHN,
        
        /// <remarks/>
        CIV,
        
        /// <remarks/>
        CMR,
        
        /// <remarks/>
        COD,
        
        /// <remarks/>
        COG,
        
        /// <remarks/>
        COK,
        
        /// <remarks/>
        COL,
        
        /// <remarks/>
        COM,
        
        /// <remarks/>
        CPV,
        
        /// <remarks/>
        CRI,
        
        /// <remarks/>
        CUB,
        
        /// <remarks/>
        CUW,
        
        /// <remarks/>
        CXR,
        
        /// <remarks/>
        CYM,
        
        /// <remarks/>
        CYP,
        
        /// <remarks/>
        CZE,
        
        /// <remarks/>
        DEU,
        
        /// <remarks/>
        DJI,
        
        /// <remarks/>
        DMA,
        
        /// <remarks/>
        DNK,
        
        /// <remarks/>
        DOM,
        
        /// <remarks/>
        DZA,
        
        /// <remarks/>
        ECU,
        
        /// <remarks/>
        EGY,
        
        /// <remarks/>
        ERI,
        
        /// <remarks/>
        ESH,
        
        /// <remarks/>
        ESP,
        
        /// <remarks/>
        EST,
        
        /// <remarks/>
        ETH,
        
        /// <remarks/>
        FIN,
        
        /// <remarks/>
        FJI,
        
        /// <remarks/>
        FLK,
        
        /// <remarks/>
        FRA,
        
        /// <remarks/>
        FRO,
        
        /// <remarks/>
        FSM,
        
        /// <remarks/>
        GAB,
        
        /// <remarks/>
        GBR,
        
        /// <remarks/>
        GEO,
        
        /// <remarks/>
        GGY,
        
        /// <remarks/>
        GHA,
        
        /// <remarks/>
        GIB,
        
        /// <remarks/>
        GIN,
        
        /// <remarks/>
        GLP,
        
        /// <remarks/>
        GMB,
        
        /// <remarks/>
        GNB,
        
        /// <remarks/>
        GNQ,
        
        /// <remarks/>
        GRC,
        
        /// <remarks/>
        GRD,
        
        /// <remarks/>
        GRL,
        
        /// <remarks/>
        GTM,
        
        /// <remarks/>
        GUF,
        
        /// <remarks/>
        GUM,
        
        /// <remarks/>
        GUY,
        
        /// <remarks/>
        HKG,
        
        /// <remarks/>
        HMD,
        
        /// <remarks/>
        HND,
        
        /// <remarks/>
        HRV,
        
        /// <remarks/>
        HTI,
        
        /// <remarks/>
        HUN,
        
        /// <remarks/>
        IDN,
        
        /// <remarks/>
        IMN,
        
        /// <remarks/>
        IND,
        
        /// <remarks/>
        IOT,
        
        /// <remarks/>
        IRL,
        
        /// <remarks/>
        IRN,
        
        /// <remarks/>
        IRQ,
        
        /// <remarks/>
        ISL,
        
        /// <remarks/>
        ISR,
        
        /// <remarks/>
        ITA,
        
        /// <remarks/>
        JAM,
        
        /// <remarks/>
        JEY,
        
        /// <remarks/>
        JOR,
        
        /// <remarks/>
        JPN,
        
        /// <remarks/>
        KAZ,
        
        /// <remarks/>
        KEN,
        
        /// <remarks/>
        KGZ,
        
        /// <remarks/>
        KHM,
        
        /// <remarks/>
        KIR,
        
        /// <remarks/>
        KNA,
        
        /// <remarks/>
        KOR,
        
        /// <remarks/>
        KWT,
        
        /// <remarks/>
        LAO,
        
        /// <remarks/>
        LBN,
        
        /// <remarks/>
        LBR,
        
        /// <remarks/>
        LBY,
        
        /// <remarks/>
        LCA,
        
        /// <remarks/>
        LIE,
        
        /// <remarks/>
        LKA,
        
        /// <remarks/>
        LSO,
        
        /// <remarks/>
        LTU,
        
        /// <remarks/>
        LUX,
        
        /// <remarks/>
        LVA,
        
        /// <remarks/>
        MAC,
        
        /// <remarks/>
        MAF,
        
        /// <remarks/>
        MAR,
        
        /// <remarks/>
        MCO,
        
        /// <remarks/>
        MDA,
        
        /// <remarks/>
        MDG,
        
        /// <remarks/>
        MDV,
        
        /// <remarks/>
        MEX,
        
        /// <remarks/>
        MHL,
        
        /// <remarks/>
        MKD,
        
        /// <remarks/>
        MLI,
        
        /// <remarks/>
        MLT,
        
        /// <remarks/>
        MMR,
        
        /// <remarks/>
        MNE,
        
        /// <remarks/>
        MNG,
        
        /// <remarks/>
        MNP,
        
        /// <remarks/>
        MOZ,
        
        /// <remarks/>
        MRT,
        
        /// <remarks/>
        MSR,
        
        /// <remarks/>
        MTQ,
        
        /// <remarks/>
        MUS,
        
        /// <remarks/>
        MWI,
        
        /// <remarks/>
        MYS,
        
        /// <remarks/>
        MYT,
        
        /// <remarks/>
        NAM,
        
        /// <remarks/>
        NCL,
        
        /// <remarks/>
        NER,
        
        /// <remarks/>
        NFK,
        
        /// <remarks/>
        NGA,
        
        /// <remarks/>
        NIC,
        
        /// <remarks/>
        NIU,
        
        /// <remarks/>
        NLD,
        
        /// <remarks/>
        NOR,
        
        /// <remarks/>
        NPL,
        
        /// <remarks/>
        NRU,
        
        /// <remarks/>
        NZL,
        
        /// <remarks/>
        OMN,
        
        /// <remarks/>
        PAK,
        
        /// <remarks/>
        PAN,
        
        /// <remarks/>
        PCN,
        
        /// <remarks/>
        PER,
        
        /// <remarks/>
        PHL,
        
        /// <remarks/>
        PLW,
        
        /// <remarks/>
        PNG,
        
        /// <remarks/>
        POL,
        
        /// <remarks/>
        PRI,
        
        /// <remarks/>
        PRK,
        
        /// <remarks/>
        PRT,
        
        /// <remarks/>
        PRY,
        
        /// <remarks/>
        PSE,
        
        /// <remarks/>
        PYF,
        
        /// <remarks/>
        QAT,
        
        /// <remarks/>
        REU,
        
        /// <remarks/>
        ROU,
        
        /// <remarks/>
        RUS,
        
        /// <remarks/>
        RWA,
        
        /// <remarks/>
        SAU,
        
        /// <remarks/>
        SDN,
        
        /// <remarks/>
        SEN,
        
        /// <remarks/>
        SGP,
        
        /// <remarks/>
        SGS,
        
        /// <remarks/>
        SHN,
        
        /// <remarks/>
        SJM,
        
        /// <remarks/>
        SLB,
        
        /// <remarks/>
        SLE,
        
        /// <remarks/>
        SLV,
        
        /// <remarks/>
        SMR,
        
        /// <remarks/>
        SOM,
        
        /// <remarks/>
        SPM,
        
        /// <remarks/>
        SRB,
        
        /// <remarks/>
        SSD,
        
        /// <remarks/>
        STP,
        
        /// <remarks/>
        SUR,
        
        /// <remarks/>
        SVK,
        
        /// <remarks/>
        SVN,
        
        /// <remarks/>
        SWE,
        
        /// <remarks/>
        SWZ,
        
        /// <remarks/>
        SXM,
        
        /// <remarks/>
        SYC,
        
        /// <remarks/>
        SYR,
        
        /// <remarks/>
        TCA,
        
        /// <remarks/>
        TCD,
        
        /// <remarks/>
        TGO,
        
        /// <remarks/>
        THA,
        
        /// <remarks/>
        TJK,
        
        /// <remarks/>
        TKL,
        
        /// <remarks/>
        TKM,
        
        /// <remarks/>
        TLS,
        
        /// <remarks/>
        TON,
        
        /// <remarks/>
        TTO,
        
        /// <remarks/>
        TUN,
        
        /// <remarks/>
        TUR,
        
        /// <remarks/>
        TUV,
        
        /// <remarks/>
        TWN,
        
        /// <remarks/>
        TZA,
        
        /// <remarks/>
        UGA,
        
        /// <remarks/>
        UKR,
        
        /// <remarks/>
        UMI,
        
        /// <remarks/>
        URY,
        
        /// <remarks/>
        USA,
        
        /// <remarks/>
        UZB,
        
        /// <remarks/>
        VAT,
        
        /// <remarks/>
        VCT,
        
        /// <remarks/>
        VEN,
        
        /// <remarks/>
        VGB,
        
        /// <remarks/>
        VIR,
        
        /// <remarks/>
        VNM,
        
        /// <remarks/>
        VUT,
        
        /// <remarks/>
        WLF,
        
        /// <remarks/>
        WSM,
        
        /// <remarks/>
        YEM,
        
        /// <remarks/>
        ZAF,
        
        /// <remarks/>
        ZMB,
        
        /// <remarks/>
        ZWE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public partial class ForeignCitizenIdentity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Document documentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Document document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("document");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public partial class Document : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentNumberField;
        
        private documentTypeEnum documentTypeField;
        
        private bool documentTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string documentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
                this.RaisePropertyChanged("documentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public documentTypeEnum documentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
                this.RaisePropertyChanged("documentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool documentTypeSpecified {
            get {
                return this.documentTypeFieldSpecified;
            }
            set {
                this.documentTypeFieldSpecified = value;
                this.RaisePropertyChanged("documentTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public enum documentTypeEnum {
        
        /// <remarks/>
        drivingLicense,
        
        /// <remarks/>
        idCard,
        
        /// <remarks/>
        passport,
        
        /// <remarks/>
        insurance,
        
        /// <remarks/>
        other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public partial class PolishCitizenIdentity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string peselField;
        
        private Document documentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string pesel {
            get {
                return this.peselField;
            }
            set {
                this.peselField = value;
                this.RaisePropertyChanged("pesel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Document document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("document");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public partial class DebtorIdentity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PolishCitizenIdentity polishCitizenIdentityField;
        
        private ForeignCitizenIdentity foreignCitizenIdentityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PolishCitizenIdentity polishCitizenIdentity {
            get {
                return this.polishCitizenIdentityField;
            }
            set {
                this.polishCitizenIdentityField = value;
                this.RaisePropertyChanged("polishCitizenIdentity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ForeignCitizenIdentity foreignCitizenIdentity {
            get {
                return this.foreignCitizenIdentityField;
            }
            set {
                this.foreignCitizenIdentityField = value;
                this.RaisePropertyChanged("foreignCitizenIdentity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public partial class Debtor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string debtorIdField;
        
        private string forenameField;
        
        private string surenameField;
        
        private DebtorIdentity debtorIdentityField;
        
        private Address residenceAddressField;
        
        private Address corespondenceAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string debtorId {
            get {
                return this.debtorIdField;
            }
            set {
                this.debtorIdField = value;
                this.RaisePropertyChanged("debtorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string forename {
            get {
                return this.forenameField;
            }
            set {
                this.forenameField = value;
                this.RaisePropertyChanged("forename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string surename {
            get {
                return this.surenameField;
            }
            set {
                this.surenameField = value;
                this.RaisePropertyChanged("surename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public DebtorIdentity debtorIdentity {
            get {
                return this.debtorIdentityField;
            }
            set {
                this.debtorIdentityField = value;
                this.RaisePropertyChanged("debtorIdentity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public Address residenceAddress {
            get {
                return this.residenceAddressField;
            }
            set {
                this.residenceAddressField = value;
                this.RaisePropertyChanged("residenceAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public Address corespondenceAddress {
            get {
                return this.corespondenceAddressField;
            }
            set {
                this.corespondenceAddressField = value;
                this.RaisePropertyChanged("corespondenceAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public partial class EconomicInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Debtor debtorField;
        
        private Liability liabilityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Debtor debtor {
            get {
                return this.debtorField;
            }
            set {
                this.debtorField = value;
                this.RaisePropertyChanged("debtor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Liability liability {
            get {
                return this.liabilityField;
            }
            set {
                this.liabilityField = value;
                this.RaisePropertyChanged("liability");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public partial class Operation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string operationIdField;
        
        private EconomicInformation addInformationField;
        
        private EconomicInformation updateInformationField;
        
        private BlockInformation blockInformationField;
        
        private InformationSelector unblockInformationField;
        
        private InformationSelector deleteInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OperationId {
            get {
                return this.operationIdField;
            }
            set {
                this.operationIdField = value;
                this.RaisePropertyChanged("OperationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public EconomicInformation addInformation {
            get {
                return this.addInformationField;
            }
            set {
                this.addInformationField = value;
                this.RaisePropertyChanged("addInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public EconomicInformation updateInformation {
            get {
                return this.updateInformationField;
            }
            set {
                this.updateInformationField = value;
                this.RaisePropertyChanged("updateInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public BlockInformation blockInformation {
            get {
                return this.blockInformationField;
            }
            set {
                this.blockInformationField = value;
                this.RaisePropertyChanged("blockInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public InformationSelector unblockInformation {
            get {
                return this.unblockInformationField;
            }
            set {
                this.unblockInformationField = value;
                this.RaisePropertyChanged("unblockInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public InformationSelector deleteInformation {
            get {
                return this.deleteInformationField;
            }
            set {
                this.deleteInformationField = value;
                this.RaisePropertyChanged("deleteInformation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.ig2big.org/ws/v1/types")]
    public partial class PackageSubmit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string packageIdField;
        
        private Operation[] operationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string packageId {
            get {
                return this.packageIdField;
            }
            set {
                this.packageIdField = value;
                this.RaisePropertyChanged("packageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("operation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Operation[] operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IG2BIG_packageSubmitRequest_outRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ms.gov.pl/ig2big/common", Order=0)]
        public RupBig.ServiceReferenceBigMain.Package packageSubmitRequest;
        
        public IG2BIG_packageSubmitRequest_outRequest() {
        }
        
        public IG2BIG_packageSubmitRequest_outRequest(RupBig.ServiceReferenceBigMain.Package packageSubmitRequest) {
            this.packageSubmitRequest = packageSubmitRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IG2BIG_packageSubmitRequest_outResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ms.gov.pl/ig2big/common", Order=0)]
        public RupBig.ServiceReferenceBigMain.Confirmation packageSubmitResponse;
        
        public IG2BIG_packageSubmitRequest_outResponse() {
        }
        
        public IG2BIG_packageSubmitRequest_outResponse(RupBig.ServiceReferenceBigMain.Confirmation packageSubmitResponse) {
            this.packageSubmitResponse = packageSubmitResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IG2BIG_packageSubmitRequest_outChannel : RupBig.ServiceReferenceBigMain.IG2BIG_packageSubmitRequest_out, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class G2BIG_packageSubmitRequest_outClient : System.ServiceModel.ClientBase<RupBig.ServiceReferenceBigMain.IG2BIG_packageSubmitRequest_out>, RupBig.ServiceReferenceBigMain.IG2BIG_packageSubmitRequest_out {
        
        public G2BIG_packageSubmitRequest_outClient() {
        }
        
        public G2BIG_packageSubmitRequest_outClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public G2BIG_packageSubmitRequest_outClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public G2BIG_packageSubmitRequest_outClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public G2BIG_packageSubmitRequest_outClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RupBig.ServiceReferenceBigMain.IG2BIG_packageSubmitRequest_outResponse RupBig.ServiceReferenceBigMain.IG2BIG_packageSubmitRequest_out.IG2BIG_packageSubmitRequest_out(RupBig.ServiceReferenceBigMain.IG2BIG_packageSubmitRequest_outRequest request) {
            return base.Channel.IG2BIG_packageSubmitRequest_out(request);
        }
        
        public RupBig.ServiceReferenceBigMain.Confirmation IG2BIG_packageSubmitRequest_out(RupBig.ServiceReferenceBigMain.Package packageSubmitRequest) {
            RupBig.ServiceReferenceBigMain.IG2BIG_packageSubmitRequest_outRequest inValue = new RupBig.ServiceReferenceBigMain.IG2BIG_packageSubmitRequest_outRequest();
            inValue.packageSubmitRequest = packageSubmitRequest;
            RupBig.ServiceReferenceBigMain.IG2BIG_packageSubmitRequest_outResponse retVal = ((RupBig.ServiceReferenceBigMain.IG2BIG_packageSubmitRequest_out)(this)).IG2BIG_packageSubmitRequest_out(inValue);
            return retVal.packageSubmitResponse;
        }
    }
}
