//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:InstalmentPlanCreate", ConfigurationName="Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOut")]
    public interface InstalmentPlanCreateOut {
        
        // CODEGEN: Generating message contract since the operation InstalmentPlanCreateOut is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOutResponse InstalmentPlanCreateOut(Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOutResponse> InstalmentPlanCreateOutAsync(Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class InstalmentPlanCreateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Admin adminField;
        
        private string kodWalutyField;
        
        private string kluczUzgodnieniaField;
        
        private PlanRat[] tabelaPlanuRatField;
        
        private DokumentPlanuRat[] tabelaDokumentowPlanuRatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Admin Admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
                this.RaisePropertyChanged("Admin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string KodWaluty {
            get {
                return this.kodWalutyField;
            }
            set {
                this.kodWalutyField = value;
                this.RaisePropertyChanged("KodWaluty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string KluczUzgodnienia {
            get {
                return this.kluczUzgodnieniaField;
            }
            set {
                this.kluczUzgodnieniaField = value;
                this.RaisePropertyChanged("KluczUzgodnienia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PlanRat[] TabelaPlanuRat {
            get {
                return this.tabelaPlanuRatField;
            }
            set {
                this.tabelaPlanuRatField = value;
                this.RaisePropertyChanged("TabelaPlanuRat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DokumentPlanuRat[] TabelaDokumentowPlanuRat {
            get {
                return this.tabelaDokumentowPlanuRatField;
            }
            set {
                this.tabelaDokumentowPlanuRatField = value;
                this.RaisePropertyChanged("TabelaDokumentowPlanuRat");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Admin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jednostkaGospodarczaField;
        
        private string iDKomunikatuField;
        
        private string iDSystemMerytorycznegoField;
        
        private string utworzonyDataField;
        
        private string utworzonyGodzField;
        
        private string uzytkownikField;
        
        private string hasloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string JednostkaGospodarcza {
            get {
                return this.jednostkaGospodarczaField;
            }
            set {
                this.jednostkaGospodarczaField = value;
                this.RaisePropertyChanged("JednostkaGospodarcza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IDSystemMerytorycznego {
            get {
                return this.iDSystemMerytorycznegoField;
            }
            set {
                this.iDSystemMerytorycznegoField = value;
                this.RaisePropertyChanged("IDSystemMerytorycznego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UtworzonyData {
            get {
                return this.utworzonyDataField;
            }
            set {
                this.utworzonyDataField = value;
                this.RaisePropertyChanged("UtworzonyData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string UtworzonyGodz {
            get {
                return this.utworzonyGodzField;
            }
            set {
                this.utworzonyGodzField = value;
                this.RaisePropertyChanged("UtworzonyGodz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Uzytkownik {
            get {
                return this.uzytkownikField;
            }
            set {
                this.uzytkownikField = value;
                this.RaisePropertyChanged("Uzytkownik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Haslo {
            get {
                return this.hasloField;
            }
            set {
                this.hasloField = value;
                this.RaisePropertyChanged("Haslo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class Komunikat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDKomunikatuField;
        
        private string rodzajKomunikatuField;
        
        private string numerKomunikatuField;
        
        private string komunikat1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDKomunikatu {
            get {
                return this.iDKomunikatuField;
            }
            set {
                this.iDKomunikatuField = value;
                this.RaisePropertyChanged("IDKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RodzajKomunikatu {
            get {
                return this.rodzajKomunikatuField;
            }
            set {
                this.rodzajKomunikatuField = value;
                this.RaisePropertyChanged("RodzajKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NumerKomunikatu {
            get {
                return this.numerKomunikatuField;
            }
            set {
                this.numerKomunikatuField = value;
                this.RaisePropertyChanged("NumerKomunikatu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Komunikat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Komunikat1 {
            get {
                return this.komunikat1Field;
            }
            set {
                this.komunikat1Field = value;
                this.RaisePropertyChanged("Komunikat1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class InstalmentPlanCreateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numerPlanuRatField;
        
        private Komunikat[] komunikatyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NumerPlanuRat {
            get {
                return this.numerPlanuRatField;
            }
            set {
                this.numerPlanuRatField = value;
                this.RaisePropertyChanged("NumerPlanuRat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Komunikat[] Komunikaty {
            get {
                return this.komunikatyField;
            }
            set {
                this.komunikatyField = value;
                this.RaisePropertyChanged("Komunikaty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class DokumentPlanuRat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numerDokumentuRozrachunkowField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NumerDokumentuRozrachunkow {
            get {
                return this.numerDokumentuRozrachunkowField;
            }
            set {
                this.numerDokumentuRozrachunkowField = value;
                this.RaisePropertyChanged("NumerDokumentuRozrachunkow");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:Common")]
    public partial class PlanRat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numerRatyField;
        
        private string terminPlatnosciField;
        
        private string kwotaPlatnosciField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NumerRaty {
            get {
                return this.numerRatyField;
            }
            set {
                this.numerRatyField = value;
                this.RaisePropertyChanged("NumerRaty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TerminPlatnosci {
            get {
                return this.terminPlatnosciField;
            }
            set {
                this.terminPlatnosciField = value;
                this.RaisePropertyChanged("TerminPlatnosci");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string KwotaPlatnosci {
            get {
                return this.kwotaPlatnosciField;
            }
            set {
                this.kwotaPlatnosciField = value;
                this.RaisePropertyChanged("KwotaPlatnosci");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InstalmentPlanCreateOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:InstalmentPlanCreate", Order=0)]
        public Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateRequest InstalmentPlanCreateRequest;
        
        public InstalmentPlanCreateOutRequest() {
        }
        
        public InstalmentPlanCreateOutRequest(Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateRequest InstalmentPlanCreateRequest) {
            this.InstalmentPlanCreateRequest = InstalmentPlanCreateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InstalmentPlanCreateOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ms.gov.pl:EX2PSCD:InstalmentPlanCreate", Order=0)]
        public Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateResponse InstalmentPlanCreateResponse;
        
        public InstalmentPlanCreateOutResponse() {
        }
        
        public InstalmentPlanCreateOutResponse(Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateResponse InstalmentPlanCreateResponse) {
            this.InstalmentPlanCreateResponse = InstalmentPlanCreateResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InstalmentPlanCreateOutChannel : Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOut, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InstalmentPlanCreateOutClient : System.ServiceModel.ClientBase<Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOut>, Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOut {
        
        public InstalmentPlanCreateOutClient() {
        }
        
        public InstalmentPlanCreateOutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InstalmentPlanCreateOutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InstalmentPlanCreateOutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InstalmentPlanCreateOutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOutResponse Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOut.InstalmentPlanCreateOut(Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOutRequest request) {
            return base.Channel.InstalmentPlanCreateOut(request);
        }
        
        public Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateResponse InstalmentPlanCreateOut(Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateRequest InstalmentPlanCreateRequest) {
            Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOutRequest inValue = new Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOutRequest();
            inValue.InstalmentPlanCreateRequest = InstalmentPlanCreateRequest;
            Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOutResponse retVal = ((Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOut)(this)).InstalmentPlanCreateOut(inValue);
            return retVal.InstalmentPlanCreateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOutResponse> Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOut.InstalmentPlanCreateOutAsync(Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOutRequest request) {
            return base.Channel.InstalmentPlanCreateOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOutResponse> InstalmentPlanCreateOutAsync(Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateRequest InstalmentPlanCreateRequest) {
            Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOutRequest inValue = new Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOutRequest();
            inValue.InstalmentPlanCreateRequest = InstalmentPlanCreateRequest;
            return ((Ex2PscdInterface.Ex2PscdInstalmentPlanCreateOutService.InstalmentPlanCreateOut)(this)).InstalmentPlanCreateOutAsync(inValue);
        }
    }
}
